import{FORMATS_COMPETITION}from'../js/format_competition.js';document.addEventListener('DOMContentLoaded',()=>{const selectFormatEl=document.getElementById('selectFormatViz');const selectNbParticipantsEl=document.getElementById('selectNbParticipantsViz');const chkAfficherBibEl=document.getElementById('chkAfficherBibViz');const zoneVisualisationEl=document.getElementById('zoneVisualisation');const zoneClassementEl=document.getElementById('zoneClassementTheorique');for(const formatKey in FORMATS_COMPETITION){const option=document.createElement('option');option.value=formatKey;option.textContent=FORMATS_COMPETITION[formatKey].nomFormat;selectFormatEl.appendChild(option);}
selectFormatEl.addEventListener('change',()=>{chargerOptionsNbParticipants();genererVisualisation();});selectNbParticipantsEl.addEventListener('change',genererVisualisation);chkAfficherBibEl.addEventListener('change',genererVisualisation);chargerOptionsNbParticipants();genererVisualisation();function chargerOptionsNbParticipants(){const formatKey=selectFormatEl.value;const formatConfig=FORMATS_COMPETITION[formatKey];selectNbParticipantsEl.innerHTML='';if(formatConfig&&formatConfig.variantesParNbParticipants){const variantesTriees=Object.entries(formatConfig.variantesParNbParticipants).sort(([,a],[,b])=>a.nb_participants-b.nb_participants);variantesTriees.forEach(([nomVariante,config])=>{const option=document.createElement('option');option.value=nomVariante;option.textContent=config.description||`${config.nb_participants} participants`;selectNbParticipantsEl.appendChild(option);});}}
function genererVisualisation(){zoneVisualisationEl.innerHTML='';zoneClassementEl.querySelector('table')?.remove();const formatKey=selectFormatEl.value;const nomVariante=selectNbParticipantsEl.value;const afficherBib=chkAfficherBibEl.checked;if(!formatKey||!nomVariante){return;}
const formatConfig=FORMATS_COMPETITION[formatKey];const varianteConfig=formatConfig.variantesParNbParticipants[nomVariante];if(!varianteConfig){return;}
const allRankedCompetitorsViz=[];const nbParticipantsReel=varianteConfig.nb_participants;const maxTTARendre=nbParticipantsReel+4;for(let i=1;i<=maxTTARendre;i++){allRankedCompetitorsViz.push({rank:i,bib:i.toString()});}
const getCompetitorByVizRank=(rankTT)=>allRankedCompetitorsViz.find(c=>c.rank===rankTT)||{rank:0,bib:'?'};const structureTableaux={};varianteConfig.phases.forEach(phaseConf=>{structureTableaux[phaseConf.cle]={name:phaseConf.nom,heats:[]};for(let i=0;i<phaseConf.nbSeries;i++){const nomSerie=`S${phaseConf.nomSeriesCommenceA + i}`;structureTableaux[phaseConf.cle].heats.push({name:nomSerie,competitors:Array(4).fill(null).map(()=>({bib:'-',typeRemplissage:'placeholder',sourceInfo:'Vide'}))});}});if(varianteConfig.seedingInitial){const premierePhaseCle=varianteConfig.phases[0].cle;varianteConfig.seedingInitial.forEach(seedingSerieConf=>{const targetHeat=structureTableaux[premierePhaseCle]?.heats[seedingSerieConf.serieIndexDansPhase];if(targetHeat){seedingSerieConf.slots.forEach(slotConf=>{const comp=getCompetitorByVizRank(slotConf.rangTT);const slotIndex=slotConf.prioAffichage-1;targetHeat.competitors[slotIndex]={bib:comp.bib,typeRemplissage:'seeded',sourceInfo:`TOP ${slotConf.rangTT}`};});}});}
if(varianteConfig.preRemplissagePhasesSuivantes){varianteConfig.preRemplissagePhasesSuivantes.forEach(preRemplissageConf=>{const targetHeat=structureTableaux[preRemplissageConf.phaseCibleCle]?.heats[preRemplissageConf.serieCibleIndex];if(targetHeat){preRemplissageConf.slots.forEach(slotConf=>{const comp=getCompetitorByVizRank(slotConf.rangTT);const slotIndex=slotConf.prioAffichage-1;targetHeat.competitors[slotIndex]={bib:comp.bib,typeRemplissage:'bye',sourceInfo:`TOP ${slotConf.rangTT}`};});}});}
if(varianteConfig.progressions){varianteConfig.progressions.forEach(progressionRule=>{if(!progressionRule.phaseSourceCle||!progressionRule.phaseCibleCle)return;const phaseSourceKey=progressionRule.phaseSourceCle;const phaseCibleKey=progressionRule.phaseCibleCle;let reglesApplicables=null;if(progressionRule.regles){reglesApplicables=progressionRule.regles;}else if(formatConfig.schemasCommuns&&progressionRule.refSchemaCommun){reglesApplicables=formatConfig.schemasCommuns[progressionRule.refSchemaCommun]?.regles;}
if(!reglesApplicables)return;reglesApplicables.forEach(regleSerieCible=>{const targetHeat=structureTableaux[phaseCibleKey]?.heats[regleSerieCible.serieCibleIndex];if(!targetHeat)return;regleSerieCible.groupesDeSeeding.forEach(groupe=>{const participantsCandidats=[];groupe.sources.forEach(sourceInfo=>{const serieSource=structureTableaux[phaseSourceKey]?.heats[sourceInfo.serieSourceIndex];if(!serieSource)return;const competiteursValidesSource=[...serieSource.competitors].filter(c=>c.typeRemplissage!=='placeholder'&&c.bib!=='-').sort((a,b)=>parseInt(a.bib)-parseInt(b.bib));const qualifieSimule=competiteursValidesSource[sourceInfo.rangDansSerieSource-1];if(qualifieSimule){participantsCandidats.push({bib:qualifieSimule.bib,rangSource:sourceInfo.rangDansSerieSource,serieSourceNom:serieSource.name});}});participantsCandidats.sort((a,b)=>parseInt(a.bib)-parseInt(b.bib));groupe.slotsCibles.forEach((slotCibleIndex,i)=>{const candidatAssigne=participantsCandidats[i];if(candidatAssigne){let suffixeOrdinal;switch(candidatAssigne.rangSource){case 1:suffixeOrdinal="er";break;case 2:suffixeOrdinal="nd";break;default:suffixeOrdinal="e";}
const triTTIndicator=groupe.sources.length>1?" (rangTT)":"";const sourceInfoString=`${candidatAssigne.rangSource}${suffixeOrdinal} de ${candidatAssigne.serieSourceNom}${triTTIndicator}`;targetHeat.competitors[slotCibleIndex]={bib:candidatAssigne.bib,typeRemplissage:'progressed',sourceInfo:sourceInfoString};}});});});});}
const PrioColorsClasses=[{class:'prio-red'},{class:'prio-green'},{class:'prio-blue'},{class:'prio-yellow'}];varianteConfig.phases.forEach(phaseConf=>{const phaseData=structureTableaux[phaseConf.cle];const roundContainer=document.createElement('div');roundContainer.classList.add('round-container-viz');const roundHeader=document.createElement('div');roundHeader.classList.add('round-header-viz',phaseConf.cle.toLowerCase());roundHeader.textContent=phaseData.name;roundContainer.appendChild(roundHeader);const heatsList=document.createElement('div');heatsList.classList.add('heats-list-viz');phaseData.heats.forEach(heat=>{const heatBlock=document.createElement('div');heatBlock.classList.add('heat-block-viz');const heatHeader=document.createElement('div');heatHeader.classList.add('heat-header-viz');heatHeader.textContent=heat.name;heatBlock.appendChild(heatHeader);const table=document.createElement('table');table.classList.add('heat-table-viz');let tbodyHtml='';heat.competitors.forEach((comp,compIdx)=>{const prioColorConfig=PrioColorsClasses[compIdx%PrioColorsClasses.length];const colorClass=prioColorConfig.class;const prioNumber=compIdx+1;tbodyHtml+=`<tr>
                                <td class="col-prio">
                                    <span class="couleur-box ${colorClass}">${prioNumber}</span>
                                </td>
                                <td class="cell-source">${comp.sourceInfo || 'N/A'}</td>`;if(afficherBib){tbodyHtml+=`<td class="cell-${comp.typeRemplissage || 'placeholder'}">${comp.bib}</td>`;}
tbodyHtml+=`</tr>`;});let headerHtml=`<thead><tr>
                                <th class="col-prio-header">Prio</th>
                                <th class="col-source-header">Origine</th>`;if(afficherBib){headerHtml+=`<th class="col-bib-header">Bib n°</th>`;}
headerHtml+=`</tr></thead>`;table.innerHTML=headerHtml+`<tbody>${tbodyHtml}</tbody>`;heatBlock.appendChild(table);heatsList.appendChild(heatBlock);});roundContainer.appendChild(heatsList);zoneVisualisationEl.appendChild(roundContainer);});genererEtAfficherClassementFinalTheorique(varianteConfig,allRankedCompetitorsViz,structureTableaux);}
function genererEtAfficherClassementFinalTheorique(varianteConfig,allCompetitors,structureTableauxRemplis){const tableClassement=document.createElement('table');let html=`<thead><tr><th>Rang</th><th>Dossard (RangTT)</th><th>Source</th></tr></thead><tbody>`;const classementFinalTheo=[];const dejaClassesTT=new Set();const nbParticipantsReel=varianteConfig.nb_participants;if(varianteConfig.reglesClassementFinal){varianteConfig.reglesClassementFinal.forEach(regle=>{let participantsSources=[];if(regle.nomSerieSource){const nomSerie=regle.nomSerieSource;let serieSourceTrouvee=null;for(const phaseKey in structureTableauxRemplis){const serie=structureTableauxRemplis[phaseKey].heats.find(h=>h.name===nomSerie);if(serie){serieSourceTrouvee=serie;break;}}
if(serieSourceTrouvee){const competiteursTries=serieSourceTrouvee.competitors.filter(c=>c.typeRemplissage!=='placeholder'&&c.bib!=='-').sort((a,b)=>parseInt(a.bib)-parseInt(b.bib));const competiteur=competiteursTries[regle.rangDansSerieSource-1];if(competiteur){participantsSources.push({bib:competiteur.bib,detailsSource:`${nomSerie} - ${regle.rangDansSerieSource}e`});}}}else if(regle.sourceType==="ELIMINE_PHASE"){const phaseSourceData=structureTableauxRemplis[regle.phaseCleSource];if(phaseSourceData){const seriesAChercher=regle.phaseCleSerieSource!==undefined?[phaseSourceData.heats[regle.phaseCleSerieSource]]:phaseSourceData.heats;seriesAChercher.forEach(serie=>{if(!serie)return;const competiteursTries=serie.competitors.filter(c=>c.typeRemplissage!=='placeholder'&&c.bib!=='-').sort((a,b)=>parseInt(a.bib)-parseInt(b.bib));const elimine=competiteursTries[regle.rangDansSerieSource-1];if(elimine){const triTTIndicator=regle.triSecondaire==="rangTT"?" (rangTT)":"";participantsSources.push({bib:elimine.bib,detailsSource:`${serie.name} - ${regle.rangDansSerieSource}e${triTTIndicator}`});}});if(regle.triSecondaire==="rangTT"){participantsSources.sort((a,b)=>parseInt(a.bib)-parseInt(b.bib));}}}
const rangs=regle.rangFinalAttendu?[regle.rangFinalAttendu]:(regle.rangsFinauxPlage||[]);participantsSources.forEach((participant,index)=>{const rangFinal=rangs[0]+index;if(rangFinal&&!dejaClassesTT.has(parseInt(participant.bib))){classementFinalTheo.push({rangFinal:rangFinal,bib:participant.bib,detailsSource:participant.detailsSource});dejaClassesTT.add(parseInt(participant.bib));}});});}
const participantsDansSeries=new Set();Object.values(structureTableauxRemplis).forEach(phase=>{phase.heats.forEach(heat=>{heat.competitors.forEach(comp=>{if(comp.bib!=='-')participantsDansSeries.add(parseInt(comp.bib));});});});let rangActuel=nbParticipantsReel+1;allCompetitors.filter(c=>c.rank>nbParticipantsReel).sort((a,b)=>a.rank-b.rank).forEach(compTT=>{if(!dejaClassesTT.has(compTT.rank)){classementFinalTheo.push({rangFinal:rangActuel++,bib:compTT.bib,detailsSource:"Time Trial"});}});classementFinalTheo.sort((a,b)=>a.rangFinal-b.rangFinal).forEach(item=>{html+=`<tr><td>${item.rangFinal}</td><td>${item.bib}</td><td>${item.detailsSource}</td></tr>`;});html+=`</tbody>`;tableClassement.innerHTML=html;zoneClassementEl.appendChild(tableClassement);}});