import{FORMATS_COMPETITION}from'./format_competition.js';import{timeToSeconds,secondsToTime,notifyError}from'./utils.js';import{HeatState,SpecialStatus,statusOrder}from'./constants.js';class ZoneParcours{constructor(id,nomAffichage,type,numeroPorte=0,couleurPorte=''){this.id=id;this.nomAffichage=nomAffichage;this.type=type;this.numeroPorte=numeroPorte;this.couleurPorte=couleurPorte;}}
class ConfigurationPenalites{static PENALTIES_EXCLUDING_PROGRESSION=new Set([SpecialStatus.DNS,SpecialStatus.DQB]);static genererSequenceZones(nombrePortes,rollZoneApresPorteNum,detailportes=null){const detailPortes=detailportes!==null?detailportes:'0'.repeat(nombrePortes+2);const zones=[];zones.push(new ZoneParcours('start','Start','START'));const hasRollZone=rollZoneApresPorteNum!==-1&&rollZoneApresPorteNum!==null;let rollInseree=false;if(hasRollZone&&rollZoneApresPorteNum===0){zones.push(new ZoneParcours('roll_p0','ROLL','ROLL'));rollInseree=true;}
for(let i=1;i<=nombrePortes;i++){zones.push(new ZoneParcours(`p${i}`,`Porte ${i}`,'PORTE',i,detailPortes[i-1]));if(i===rollZoneApresPorteNum&&!rollInseree){zones.push(new ZoneParcours(`roll_p${i}`,'ROLL','ROLL'));rollInseree=true;}}
if(hasRollZone&&!rollInseree&&nombrePortes>0&&rollZoneApresPorteNum>=nombrePortes){zones.push(new ZoneParcours(`roll_p${nombrePortes}`,'ROLL','ROLL'));}else if(hasRollZone&&!rollInseree&&nombrePortes===0&&rollZoneApresPorteNum>=0){zones.push(new ZoneParcours('roll_p0','ROLL','ROLL'));}
return zones;}}
class PenaltyEncoder{static encode(penaltyString){if(!penaltyString||penaltyString.split('').every(p=>p==='0')){return 0;}
const totalZones=penaltyString.length
let ralCount=0;let fltCount=0;let ralMask=0;let fltMask=0;const penalties=penaltyString.split('');for(let i=0;i<totalZones;i++){const pos=totalZones-1-i;if(penalties[i]==='5'){ralCount++;ralMask|=(1<<pos);}else if(penalties[i]==='2'){fltCount++;fltMask|=(1<<pos);}}
const score=(ralCount<<28)|(fltCount<<24)|(ralMask<<12)|fltMask;return score;}}
class Participant{constructor(categorieCle,rankTT,bib,name,nom,prenom,sexe,club,selected=false,codeBateau=null,matric,nation,statusTT=null,sourceCsv=null){this.id=codeBateau?String(codeBateau):`${categorieCle}-${bib || 'NOBIB'}`;this.categorieCle=categorieCle;this.rankTT=parseInt(rankTT,10)||0;this.bib=bib||'-';this.name=name||'N/A';this.nom=nom||'';this.prenom=prenom||'';this.club=club||'';this.sexe=sexe||'';this.selected=selected;this.matric=matric||'';this.nation=nation||'';this.heatHistory=[];this.finalRankInCategory=null;this.codeBateau=codeBateau?String(codeBateau):null;this.statusTT=statusTT;this.sourceCsv=sourceCsv;}
addHeatResultToHistory(roundKey,heatName,prioDepart,order,penalty,heatRank){this.heatHistory=this.heatHistory.filter(h=>!(h.roundKey===roundKey&&h.heatName===heatName));this.heatHistory.push({roundKey,heatName,prioDepart,order,penalty,heatRank});}
resetCompetitionState(){this.heatHistory=[];this.finalRankInCategory=null;}}
class Serie{constructor(name,roundKey,numberOfSlots=4){this.id=null;this.name=name;this.roundKey=roundKey;this.startTime="";this.etat=HeatState.EN_ATTENTE;this.globalHeatNumber=null;this.slots=Array(numberOfSlots).fill(null).map(()=>({participant:null,prioDepart:null,heatResult:{order:null,penalty:null,specialStatus:null,finalRank:'-'}}));}
assignParticipantToSlot(participantInstance,slotIndex,prioDepart){if(slotIndex>=0&&slotIndex<this.slots.length){this.slots[slotIndex]={participant:participantInstance,prioDepart:prioDepart,heatResult:{order:null,penalty:null,specialStatus:null,finalRank:'-'}};}else{console.error(`[Serie ${this.name}] Index de slot invalide: ${slotIndex}`);}}
calculateAndApplyRanking(){const activeSlots=this.slots.filter(slot=>slot&&slot.participant&&slot.participant.rankTT>0);const hasAnyResultEntered=activeSlots.some(slot=>slot.heatResult.order||slot.heatResult.specialStatus);if(!hasAnyResultEntered){this.slots.forEach(slot=>{slot.heatResult.finalRank='-';});return;}
activeSlots.forEach(slot=>{slot.heatResult.penaltyScore=PenaltyEncoder.encode(slot.heatResult.penalty)||0;});activeSlots.sort((slotA,slotB)=>{const resultA=slotA.heatResult;const resultB=slotB.heatResult;const aHasResult=resultA.order||resultA.specialStatus;const bHasResult=resultB.order||resultB.specialStatus;if(aHasResult&&!bHasResult)return-1;if(!aHasResult&&bHasResult)return 1;if(!aHasResult&&!bHasResult){const rankTTA=slotA.participant.rankTT>0?slotA.participant.rankTT:Infinity;const rankTTB=slotB.participant.rankTT>0?slotB.participant.rankTT:Infinity;return rankTTA-rankTTB;}
const statusA=statusOrder[resultA.specialStatus]||0;const statusB=statusOrder[resultB.specialStatus]||0;if(statusA!==statusB){return statusA-statusB;}
const scoreA=resultA.penaltyScore||0;const scoreB=resultB.penaltyScore||0;if(scoreA!==scoreB){return scoreA-scoreB;}
const orderA=resultA.order?parseInt(resultA.order,10):Infinity;const orderB=resultB.order?parseInt(resultB.order,10):Infinity;if(orderA!==orderB){return orderA-orderB;}
const rankTTA=slotA.participant.rankTT>0?slotA.participant.rankTT:Infinity;const rankTTB=slotB.participant.rankTT>0?slotB.participant.rankTT:Infinity;return rankTTA-rankTTB;});activeSlots.forEach((slot,index)=>{const result=slot.heatResult;if(result.order||result.specialStatus){slot.heatResult.finalRank=(index+1).toString();}else{slot.heatResult.finalRank='-';}});this.slots.forEach(slot=>{if(!activeSlots.includes(slot)){slot.heatResult.finalRank=slot.heatResult.specialStatus||'-';}});}
RankingValidated(){this.calculateAndApplyRanking();this.slots.forEach(slot=>{if(slot.participant&&slot.participant.rankTT>0&&slot.participant.addHeatResultToHistory){slot.participant.addHeatResultToHistory(this.roundKey,this.name,slot.prioDepart,slot.heatResult.order,slot.heatResult.penalty,slot.heatResult.finalRank);}});}
areAllActiveResultsEntered(){return this.slots.every(slot=>{if(!slot.participant||!slot.participant.id||slot.participant.rankTT===0)return true;const result=slot.heatResult;const hasOrder=result.order&&result.order!=="";const hasSpecialStatus=result.specialStatus&&result.specialStatus!=="";return hasOrder||hasSpecialStatus;});}}
class CategorieCompetition{constructor(cle,nom,nomCourt,numCompetitorsInHeats,configVariante,nomVariante,ordre,schemasCommunsGlobaux=null){this.cle=cle;this.nom=nom;this.nomCourt=nomCourt;this.numCompetitorsInHeats=parseInt(numCompetitorsInHeats,10);this.configVariante=configVariante;this.nomVariante=nomVariante;this.ordre=ordre;this._schemasCommunsGlobaux=schemasCommunsGlobaux;this.masterParticipantList=[];this.rounds={};this.finalRanking=[];this.hasClub=false;this.hasSexe=false;this.hasNation=false;this.placeholderParticipant=new Participant(this.cle,0,'-','-','-','-','','',false,null,'','');}
buildMasterListFromAPIData(participantsAPI){this.masterParticipantList=participantsAPI.map(p=>{const ttStatus=(typeof p.Tps_chrono==='string')?p.Tps_chrono:null;return new Participant(this.cle,p.calculated_rang,p.Dossard,`${(p.Nom || 'N/A').toUpperCase()} ${p.Prenom || ''}`.trim(),`${(p.Nom || 'N/A').toUpperCase()}`.trim(),`${p.Prenom || ''}`.trim(),p.Sexe,p.Club,p.selected,p.Code_bateau,p.Matric,p.Nation,ttStatus,p.Source_csv);});this.masterParticipantList.sort((a,b)=>a.rankTT-b.rankTT);this.computeFieldPresenceFlags();}
computeFieldPresenceFlags(){this.hasClub=this.masterParticipantList.some(p=>p.club&&p.club.trim()!=='');this.hasSexe=this.masterParticipantList.some(p=>p.sexe&&p.sexe.trim()!=='');this.hasNation=this.masterParticipantList.some(p=>p.nation&&p.nation.trim()!=='');}
initializeRoundsAndSeed(){if(!this.configVariante||!this.configVariante.phases){console.error(`[${this.cle}] Aucune configVariante.phases pour initialiser.`);this.rounds={};this.generateAndStoreFinalRanking();return;}
this.rounds={};this.configVariante.phases.forEach(phaseConfig=>{const currentRound={name:phaseConfig.nom,nom_court:phaseConfig.nom_court||phaseConfig.nom,nom_inter:phaseConfig.nom_inter||"",heats:[]};for(let i=0;i<phaseConfig.nbSeries;i++){const nomSerie=`S${phaseConfig.nomSeriesCommenceA + i}`;const newSerie=new Serie(nomSerie,phaseConfig.cle);currentRound.heats.push(newSerie);}
this.rounds[phaseConfig.cle]=currentRound;});const participantsEligiblesPourSeries=this.masterParticipantList.filter(p=>p.selected===true&&p.rankTT>0).sort((a,b)=>a.rankTT-b.rankTT).slice(0,this.numCompetitorsInHeats);const mapEligiblesParRankTT=new Map(participantsEligiblesPourSeries.map(p=>[p.rankTT,p]));if(this.configVariante.seedingInitial&&this.configVariante.seedingInitial.length>0){const premierePhaseCle=this.configVariante.phases[0].cle;const premierePhaseData=this.rounds[premierePhaseCle];if(premierePhaseData){this.configVariante.seedingInitial.forEach(seedingSerieConfig=>{const targetSerie=premierePhaseData.heats[seedingSerieConfig.serieIndexDansPhase];if(targetSerie){seedingSerieConfig.slots.forEach(slotConfig=>{const slotIndex=slotConfig.prioAffichage-1;const participantForSlot=mapEligiblesParRankTT.get(slotConfig.rangTT)||null;targetSerie.assignParticipantToSlot(participantForSlot||this.placeholderParticipant,slotIndex,slotConfig.prioAffichage);});}});}}
if(this.configVariante.preRemplissagePhasesSuivantes){this.configVariante.preRemplissagePhasesSuivantes.forEach(preRemplissageConfig=>{const phaseCibleData=this.rounds[preRemplissageConfig.phaseCibleCle];if(phaseCibleData){const serieCible=phaseCibleData.heats[preRemplissageConfig.serieCibleIndex];if(serieCible){preRemplissageConfig.slots.forEach(slotConfig=>{const slotIndex=slotConfig.prioAffichage-1;const participantForSlot=mapEligiblesParRankTT.get(slotConfig.rangTT)||null;serieCible.assignParticipantToSlot(participantForSlot||this.placeholderParticipant,slotIndex,slotConfig.prioAffichage);});}}});}
this.generateAndStoreFinalRanking();}
generateAndStoreFinalRanking(){this.finalRanking=[];const participantsDejaClasses=new Set();if(this.configVariante&&this.configVariante.type==="brassage"){const participantsActifs=this.masterParticipantList.filter(p=>p.selected===true&&p.rankTT>0);const statsParParticipant={};participantsActifs.forEach(p=>{statsParParticipant[p.id]={participant:p,totalPoints:0,manchesCourues:0,victoiresPhase:0,secondesPlacesPhase:0,detailPlaces:{}};});this.configVariante.phases.forEach(phase=>{const phaseData=this.rounds[phase.cle];if(!phaseData)return;phaseData.heats.forEach(serie=>{if(serie.etat===HeatState.OFFICIEL){serie.slots.forEach(slot=>{if(slot.participant&&slot.participant.id&&slot.heatResult&&slot.heatResult.finalRank!=='-'){const pStats=statsParParticipant[slot.participant.id];if(pStats){let rankInHeat=parseInt(slot.heatResult.finalRank,10);if(!isNaN(rankInHeat)){const points=(rankInHeat===1)?0:rankInHeat;pStats.totalPoints+=points;pStats.manchesCourues++;pStats.detailPlaces[phase.nom_court]=rankInHeat;if(rankInHeat===1)pStats.victoiresPhase++;if(rankInHeat===2)pStats.secondesPlacesPhase++;}}}});}});});const listePourClassement=Object.values(statsParParticipant).filter(p=>p.manchesCourues>0);listePourClassement.sort((a,b)=>{if(a.manchesCourues!==b.manchesCourues)return b.manchesCourues-a.manchesCourues;if(a.totalPoints!==b.totalPoints)return a.totalPoints-b.totalPoints;if(a.victoiresPhase!==b.victoiresPhase)return b.victoiresPhase-a.victoiresPhase;if(a.secondesPlacesPhase!==b.secondesPlacesPhase)return b.secondesPlacesPhase-a.secondesPlacesPhase;return a.participant.rankTT-b.participant.rankTT;});let currentIndex=1;listePourClassement.forEach((item)=>{item.rangFinal=currentIndex++;item.participant.finalRankInCategory=item.rangFinal;let placesStr=Object.entries(item.detailPlaces).map(([m,place])=>`${m}:${place}`).join(' ');item.detailsSource=`${item.totalPoints} pts (${placesStr})`;item.InterSource="BRAS";this.finalRanking.push(item);participantsDejaClasses.add(item.participant.id);});const participantsNonClasses=participantsActifs.filter(p=>!participantsDejaClasses.has(p.id));participantsNonClasses.sort((a,b)=>a.rankTT-b.rankTT);participantsNonClasses.forEach(p=>{const sourceName=p.sourceCsv?p.sourceCsv:"Time Trial";this.finalRanking.push({rangFinal:currentIndex++,participant:p,totalPoints:null,detailPlaces:{},detailsSource:sourceName,InterSource:"QUAL",lastStatus:p.statusTT||null});});return this.finalRanking;}
if(!this.configVariante||!this.configVariante.reglesClassementFinal){this.masterParticipantList.filter(p=>p.rankTT>0).sort((a,b)=>a.rankTT-b.rankTT).forEach((participant,index)=>{const sourceName=participant.sourceCsv?participant.sourceCsv:"Time Trial";this.finalRanking.push({rangFinal:index+1,participant:participant,detailsSource:sourceName,InterSource:"QUAL",lastStatus:participant.statusTT||null});participant.finalRankInCategory=index+1;});const dqbEntriesSimple=this.finalRanking.filter(item=>item.participant&&item.lastStatus===SpecialStatus.DQB);if(dqbEntriesSimple.length>0){this.finalRanking=this.finalRanking.filter(item=>!(item.participant&&item.lastStatus===SpecialStatus.DQB));this.finalRanking.forEach((item,index)=>{item.rangFinal=index+1;if(item.participant)item.participant.finalRankInCategory=index+1;});dqbEntriesSimple.sort((a,b)=>a.participant.name.localeCompare(b.participant.name));let nextRankSimple=this.finalRanking.length+1;dqbEntriesSimple.forEach(item=>{item.rangFinal=nextRankSimple;item.detailsSource=`DQB - ${item.detailsSource}`;item.participant.finalRankInCategory=nextRankSimple;this.finalRanking.push(item);nextRankSimple++;});}
return this.finalRanking;}
const participantsDansLesSeries=this.masterParticipantList.filter(p=>p.selected===true&&p.rankTT>0).sort((a,b)=>a.rankTT-b.rankTT).slice(0,this.numCompetitorsInHeats);const idsParticipantsDansLesSeries=new Set(participantsDansLesSeries.map(p=>p.id));const nbPlaceholdersFinaux=participantsDansLesSeries.length;for(let i=1;i<=nbPlaceholdersFinaux;i++){const reglePourCeRang=this.configVariante.reglesClassementFinal.find(r=>(r.rangFinalAttendu===i)||(r.rangsFinauxPlage&&i>=r.rangsFinauxPlage[0]&&i<=r.rangsFinauxPlage[1]));let sourceAttendue="Séries";if(reglePourCeRang){if(reglePourCeRang.nomSerieSource)sourceAttendue=`Attente ${reglePourCeRang.nomSerieSource}`;else if(reglePourCeRang.phaseCleSource)sourceAttendue=`Attente Élim. ${reglePourCeRang.phaseCleSource}`;}
this.finalRanking.push({rangFinal:i,participant:null,detailsSource:sourceAttendue,InterSource:null});}
this.configVariante.reglesClassementFinal.sort((a,b)=>(a.rangFinalAttendu||a.rangsFinauxPlage[0])-(b.rangFinalAttendu||b.rangsFinauxPlage[0])).forEach(regle=>{let competiteursCandidatsPourRegle=[];if(regle.nomSerieSource){const infoSerieSource=this._findSerieEtSaPhaseParNom(regle.nomSerieSource);if(infoSerieSource&&infoSerieSource.serie.etat===HeatState.OFFICIEL){const slotsTries=infoSerieSource.serie.slots.filter(s=>s.participant&&s.participant.rankTT>0).sort((a,b)=>{const rankA=parseInt(a.heatResult.finalRank,10);const rankB=parseInt(b.heatResult.finalRank,10);const isANumeric=!isNaN(rankA);const isBNumeric=!isNaN(rankB);if(isANumeric&&isBNumeric)return rankA-rankB;if(isANumeric)return-1;if(isBNumeric)return 1;return String(a.heatResult.finalRank).localeCompare(String(b.heatResult.finalRank));});const slotCandidat=slotsTries[regle.rangDansSerieSource-1];if(slotCandidat&&!participantsDejaClasses.has(slotCandidat.participant.id)){competiteursCandidatsPourRegle.push({participant:slotCandidat.participant,details:`${infoSerieSource.phase.name} (${regle.nomSerieSource}) - ${regle.rangDansSerieSource}e`,InterPhase:infoSerieSource.phase.nom_inter||"",lastPenalty:slotCandidat.heatResult.penalty,lastStatus:slotCandidat.heatResult.specialStatus});}}}else if(regle.sourceType==="ELIMINE_PHASE"&&regle.phaseCleSource&&regle.rangsFinauxPlage){const phaseSourceData=this.rounds[regle.phaseCleSource];if(phaseSourceData&&phaseSourceData.heats.every(h=>h.etat===HeatState.OFFICIEL)){let eliminesDePhase=[];phaseSourceData.heats.forEach(serie=>{serie.slots.forEach(slot=>{if(slot.participant&&slot.participant.rankTT>0&&slot.heatResult.finalRank&&parseInt(slot.heatResult.finalRank,10)===regle.rangDansSerieSource&&!participantsDejaClasses.has(slot.participant.id)){eliminesDePhase.push({participant:slot.participant,serieNom:serie.name,phaseNom:phaseSourceData.name,InterPhase:phaseSourceData.nom_inter||"",lastPenalty:slot.heatResult.penalty,lastStatus:slot.heatResult.specialStatus});}});});if(regle.triSecondaire==="rangTT"){eliminesDePhase.sort((a,b)=>a.participant.rankTT-b.participant.rankTT);}
eliminesDePhase.forEach(elim=>{competiteursCandidatsPourRegle.push({participant:elim.participant,details:`${elim.phaseNom} (${elim.serieNom}) - ${regle.rangDansSerieSource}e`,InterPhase:phaseSourceData.nom_inter||"",lastPenalty:elim.lastPenalty,lastStatus:elim.lastStatus});});}}
let rangActuelPourPlage=regle.rangFinalAttendu||(regle.rangsFinauxPlage?regle.rangsFinauxPlage[0]:0);competiteursCandidatsPourRegle.forEach(candidat=>{const indexPlaceholder=this.finalRanking.findIndex(item=>item.rangFinal===rangActuelPourPlage&&item.participant===null);if(indexPlaceholder!==-1){this.finalRanking[indexPlaceholder].participant=candidat.participant;this.finalRanking[indexPlaceholder].detailsSource=candidat.details;this.finalRanking[indexPlaceholder].InterSource=candidat.InterPhase;this.finalRanking[indexPlaceholder].lastPenalty=candidat.lastPenalty;this.finalRanking[indexPlaceholder].lastStatus=candidat.lastStatus;candidat.participant.finalRankInCategory=rangActuelPourPlage;participantsDejaClasses.add(candidat.participant.id);if(regle.rangsFinauxPlage)rangActuelPourPlage++;}else{console.warn(`[${this.cle}] Classement: Placeholder non trouvé ou déjà pris pour rang ${rangActuelPourPlage} (Participant: ${candidat.participant.name})`);}});});let prochainRangAPlacer=nbPlaceholdersFinaux+1;this.masterParticipantList.filter(p=>p.rankTT>0).sort((a,b)=>a.rankTT-b.rankTT).forEach(participant=>{if(!idsParticipantsDansLesSeries.has(participant.id)){const sourceName=participant.sourceCsv?participant.sourceCsv:"Time Trial";this.finalRanking.push({rangFinal:prochainRangAPlacer,participant:participant,detailsSource:sourceName,InterSource:"QUAL"});participant.finalRankInCategory=prochainRangAPlacer;prochainRangAPlacer++;}});this.finalRanking.sort((a,b)=>a.rangFinal-b.rangFinal);const dqbEntries=this.finalRanking.filter(item=>item.participant&&item.lastStatus===SpecialStatus.DQB);if(dqbEntries.length>0){this.finalRanking=this.finalRanking.filter(item=>!(item.participant&&item.lastStatus===SpecialStatus.DQB));this.finalRanking.forEach((item,index)=>{item.rangFinal=index+1;if(item.participant)item.participant.finalRankInCategory=index+1;});dqbEntries.sort((a,b)=>a.participant.name.localeCompare(b.participant.name));let nextRank=this.finalRanking.length+1;dqbEntries.forEach(item=>{item.rangFinal=nextRank;item.detailsSource=`DQB - ${item.detailsSource}`;item.participant.finalRankInCategory=nextRank;this.finalRanking.push(item);nextRank++;});}
return this.finalRanking;}
_findSerieEtSaPhaseParNom(nomSerie){for(const phaseCle in this.rounds){const phase=this.rounds[phaseCle];const serieTrouvee=phase.heats.find(h=>h.name===nomSerie);if(serieTrouvee){return{serie:serieTrouvee,phase:phase,phaseCle:phaseCle};}}
return null;}
getSerie(roundKey,heatIndex){return this.rounds[roundKey]?.heats[heatIndex]||null;}
getSerieByName(roundKey,heatName){return this.rounds[roundKey]?.heats.find(h=>h.name===heatName)||null;}}
class ApplicationCourse{constructor(){this._subscribers=[];this.persistenceManager=null;this.param={gateCount:8,rollZoneAfterGate:2,gateProfil:"00000000",categoriesData:{},formatCompetitionActifPourRegles:null,competitionCodeFromURL:null,selectedCompetitionAPIInfo:null,apiResultsData:null,schedulesData:{},isConfigurationValidated:false,globalScheduleSettings:{defaultEcartSeriesGlobal:180,defaultEcartCategoriesGlobal:180,}};}
setUI(uiInstance){this.ui=uiInstance;}
getTotalHeatsCount(){if(!this.param.isConfigurationValidated||!this.param.categoriesData){return 0;}
const totalHeats=Object.values(this.param.categoriesData).flatMap(category=>Object.values(category.rounds||{})).reduce((acc,round)=>acc+(round.heats?.length||0),0);return totalHeats;}
_notifyHeatUpdated(categoryKey,roundKey,heatIndex){if(this.ui&&typeof this.ui._updateHeatView==='function'){const categorieInstance=this.param.categoriesData[categoryKey];const serieInstance=categorieInstance?.getSerie(roundKey,heatIndex);if(serieInstance){this.ui._updateHeatView(serieInstance,categoryKey,roundKey,heatIndex);}}}
async reinitialiserApplication(){if(!this.persistenceManager){notifyError("Erreur : Impossible de réinitialiser sans gestionnaire de persistance actif.");console.error("Tentative de réinitialisation sans persistenceManager.");return;}
try{const result=await this.persistenceManager.resetCompetitionData();if(result.success){window.location.reload();}else{notifyError(`La réinitialisation a échoué : ${result.message}`);}}catch(error){notifyError(`Une erreur critique est survenue durant la réinitialisation : ${error.message}`);}}
updateHeatsWithDBIds(heatIdMap){Object.values(this.param.categoriesData).forEach(categorie=>{Object.values(categorie.rounds).forEach(round=>{round.heats.forEach(heat=>{const clientHeatKey=`${categorie.cle}_${heat.roundKey}_${heat.name}`;if(heatIdMap[clientHeatKey]){heat.id=heatIdMap[clientHeatKey];}});});});}
updateAllHeatsState(){for(const catKey in this.param.categoriesData){const catInstance=this.param.categoriesData[catKey];const allHeatsInCategory=Object.values(catInstance.rounds).flatMap(r=>r.heats);const isBrassage=catInstance.configVariante&&catInstance.configVariante.type==="brassage";allHeatsInCategory.forEach(heat=>{if(heat.etat!==1){return;}
if(isBrassage){heat.etat=HeatState.PRET;return;}
const sourceRules=this.findSourceHeats(catInstance,heat.roundKey,heat.name);if(sourceRules.isInitialSeeding){heat.etat=HeatState.PRET;return;}
if(sourceRules.sources.length>0){const allSourcesAreValidated=sourceRules.sources.every(sourceInfo=>{const sourceHeat=catInstance.getSerieByName(sourceInfo.roundKey,sourceInfo.heatName);return sourceHeat&&sourceHeat.etat===HeatState.OFFICIEL;});if(allSourcesAreValidated){heat.etat=HeatState.PRET;}}});}}
updatePenaltyString(categoryKey,roundKey,heatIndex,competitorIndex,newPenaltyString){const categorie=this.param.categoriesData[categoryKey];const heat=categorie.getSerie(roundKey,parseInt(heatIndex,10));const slot=heat.slots[parseInt(competitorIndex,10)];if(slot){slot.heatResult.penalty=newPenaltyString;heat.calculateAndApplyRanking();if(this.persistenceManager){this.persistenceManager.updateSlotResults(heat.id,slot.prioDepart,slot.heatResult).catch(err=>notifyError(`Erreur de sauvegarde des pénalités: ${err.message}`));}
this._notifySubscribers();}}
_calculateGlobalHeatNumbers(){const allHeats=[];Object.values(this.param.categoriesData).forEach(catInstance=>{Object.values(catInstance.rounds).forEach(round=>{round.heats.forEach(heat=>{if(heat.startTime){allHeats.push(heat);}else{heat.globalHeatNumber=null;}});});});allHeats.sort((a,b)=>{const timeA=timeToSeconds(a.startTime);const timeB=timeToSeconds(b.startTime);return timeA-timeB;});allHeats.forEach((heat,index)=>{heat.globalHeatNumber=index+1;});}
findSourceHeats(catInstance,targetRoundKey,targetHeatName){const config=catInstance.configVariante;const schemasCommuns=catInstance._schemasCommunsGlobaux||{};const targetHeatIndex=catInstance.rounds[targetRoundKey]?.heats.findIndex(h=>h.name===targetHeatName);if(targetHeatIndex===-1){return{isInitialSeeding:false,sources:[]};}
const premierePhaseCle=config.phases[0]?.cle;if(targetRoundKey===premierePhaseCle){const isInitial=config.seedingInitial?.some(rule=>rule.serieIndexDansPhase===targetHeatIndex);if(isInitial){return{isInitialSeeding:true,sources:[]};}}
const sources=[];config.progressions?.forEach(progRule=>{let reglesProgressionApplicables=progRule.regles||(schemasCommuns[progRule.refSchemaCommun]?schemasCommuns[progRule.refSchemaCommun].regles:null);if(!reglesProgressionApplicables){return;}
reglesProgressionApplicables.forEach(regleSerieCible=>{if(progRule.phaseCibleCle===targetRoundKey&&regleSerieCible.serieCibleIndex===targetHeatIndex){if(regleSerieCible.groupesDeSeeding){regleSerieCible.groupesDeSeeding.forEach(groupe=>{if(groupe.sources){groupe.sources.forEach(sourceInfo=>{const sourceHeat=catInstance.rounds[progRule.phaseSourceCle]?.heats[sourceInfo.serieSourceIndex];if(sourceHeat){sources.push({roundKey:sourceHeat.roundKey,heatName:sourceHeat.name});}});}});}}});});const uniqueSources=Array.from(new Map(sources.map(s=>[`${s.roundKey}-${s.heatName}`,s])).values());return{isInitialSeeding:false,sources:uniqueSources};}
setPersistenceManager(manager){this.persistenceManager=manager;}
subscribe(callback){this._subscribers.push(callback);}
_notifySubscribers(){const etatActuel={...this.param};this._subscribers.forEach(callback=>callback(etatActuel));}
async refreshCompetitionDataFromDB(isDisplayMode=false){if(!this.persistenceManager){console.warn("Synchronisation impossible : aucun gestionnaire de persistance n'est actif.");return;}
if(!this.param.isConfigurationValidated){console.warn("Synchronisation impossible : la configuration n'est pas validée.");return;}
try{const persistedData=await this.persistenceManager.loadCategoriesData();if(persistedData&&persistedData.categoriesData){this._updateCategoriesFromData(persistedData.categoriesData,isDisplayMode);}else{console.log("Aucune nouvelle donnée à synchroniser depuis la base.");}}catch(error){console.error("La synchronisation a échoué :",error);notifyError(`Erreur lors de la synchronisation : ${error.message}`);}}
_updateCategoriesFromData(persistedCategories,isDisplayMode=false){let needsNotification=false;const allModifiedHeatsToSave=[];for(const catKey in persistedCategories){let categoryHasChanged=false;const persistedCat=persistedCategories[catKey];const catInstance=this.param.categoriesData[catKey];if(!catInstance)continue;for(const roundKey in persistedCat.rounds){const persistedRound=persistedCat.rounds[roundKey];for(const persistedHeat of persistedRound.heats){const serieInstance=catInstance.getSerieByName(roundKey,persistedHeat.name);if(!serieInstance)continue;if(serieInstance.etat!==persistedHeat.etat){serieInstance.etat=persistedHeat.etat;needsNotification=true;categoryHasChanged=true;}
let resultsChanged=false;persistedHeat.slots.forEach(persistedSlot=>{const slotIndex=persistedSlot.prioDepart-1;if(slotIndex>=0&&slotIndex<serieInstance.slots.length){const slotInstance=serieInstance.slots[slotIndex];const oldResult=JSON.stringify(slotInstance.heatResult);slotInstance.heatResult.order=persistedSlot.heatResult.order?String(persistedSlot.heatResult.order):null;slotInstance.heatResult.penalty=persistedSlot.heatResult.penalty;slotInstance.heatResult.specialStatus=persistedSlot.heatResult.specialStatus;slotInstance.heatResult.finalRank=persistedSlot.heatResult.finalRank>0?String(persistedSlot.heatResult.finalRank):(persistedSlot.heatResult.specialStatus||'-');const newResult=JSON.stringify(slotInstance.heatResult);if(oldResult!==newResult){resultsChanged=true;}}});if(resultsChanged){categoryHasChanged=true;needsNotification=true;serieInstance.calculateAndApplyRanking();}}}
const modifiedTargetHeats=this._reevaluerEtAppliquerProgressions(catInstance);if(modifiedTargetHeats.size>0){categoryHasChanged=true;this.updateAllHeatsState();const heatsToSave=Array.from(modifiedTargetHeats).filter(heat=>heat.id!==null).map(heat=>({...heat,categoryKey:catKey,roundKey:heat.roundKey}));allModifiedHeatsToSave.push(...heatsToSave);}
if(categoryHasChanged){catInstance.generateAndStoreFinalRanking();needsNotification=true;}}
if(allModifiedHeatsToSave.length>0&&this.persistenceManager&&!isDisplayMode){this.persistenceManager.saveUpdatedHeats(allModifiedHeatsToSave).catch(err=>{console.error("Erreur lors de la sauvegarde des séries mises à jour par la progression:",err);notifyError(`Une erreur est survenue lors de la sauvegarde des progressions : ${err.message}`);});}
if(needsNotification){this._notifySubscribers();}}
async initialiserApplication(){const urlParams=new URLSearchParams(window.location.search);this.param.competitionCodeFromURL=urlParams.get('competition');if(this.param.competitionCodeFromURL){await this.chargerDonneesCompetitionDepuisURL(this.param.competitionCodeFromURL);if(this.persistenceManager){try{const persistedState=await this.persistenceManager.loadFullState();if(persistedState){await this._rehydrateState(persistedState);}}catch(error){if(error.message&&error.message.toLowerCase().includes('sqlstate')){throw error;}
notifyError(`Une erreur est survenue lors du chargement de votre session précédente : ${error.message}\nL'application va démarrer avec une configuration vierge.`);}}}else{notifyError("Erreur, Aucun code de compétition.");}}
async _rehydrateState(persistedState){const{settings,schedulesData,categoriesData:persistedCategories,liveWebConfig}=persistedState;this.param.gateCount=parseInt(settings.Nombre_portes,10);this.param.rollZoneAfterGate=parseInt(settings.Roll_Zone,10);this.param.gateProfil=settings.Detail_portes||"0".repeat(this.param.gateCount);this.param.globalScheduleSettings.defaultEcartSeriesGlobal=parseInt(settings.Ecart_Series_Global,10);this.param.globalScheduleSettings.defaultEcartCategoriesGlobal=parseInt(settings.Ecart_Categories_Global,10);this.param.schedulesData=schedulesData;this.selectionnerFormatDeRegles(settings.Format,FORMATS_COMPETITION);const newCategoriesData={};for(const catKey in persistedCategories){const persistedCat=persistedCategories[catKey];const configVariante=this.param.formatCompetitionActifPourRegles.variantesParNbParticipants[persistedCat.nomVariante];if(!configVariante){console.warn(`Variante '${persistedCat.nomVariante}' non trouvée pour la catégorie ${catKey}. Catégorie ignorée.`);continue;}
let nomLongCat=this.param.apiResultsData?.statuts_categories?.[catKey]?.Nom_categorie||catKey,nomCourtCat=catKey;const catInstance=new CategorieCompetition(catKey,nomLongCat,nomCourtCat,persistedCat.numCompetitorsInHeats,configVariante,persistedCat.nomVariante,persistedCat.ordre,this.param.formatCompetitionActifPourRegles.schemasCommuns);if(this.param.apiResultsData?.resultats_par_categorie[catKey]){catInstance.buildMasterListFromAPIData(this.param.apiResultsData.resultats_par_categorie[catKey]);}
const participantsMap=new Map(catInstance.masterParticipantList.map(p=>[p.codeBateau||p.id,p]));for(const roundKey in persistedCat.rounds){const persistedRound=persistedCat.rounds[roundKey];const phaseConfig=configVariante.phases.find(p=>p.cle===roundKey);const currentRound={name:phaseConfig?.nom||roundKey,nom_court:phaseConfig?.nom_court||roundKey,nom_inter:phaseConfig?.nom_inter||"",heats:[]};for(const persistedHeat of persistedRound.heats){const serieInstance=new Serie(persistedHeat.name,roundKey);serieInstance.id=persistedHeat.id;serieInstance.startTime=persistedHeat.startTime;serieInstance.etat=persistedHeat.etat;persistedHeat.slots.forEach(persistedSlot=>{const participant=participantsMap.get(String(persistedSlot.participantCodeBateau));const slotIndex=persistedSlot.prioDepart-1;if(slotIndex>=0&&slotIndex<serieInstance.slots.length){const heatResultFromDB=persistedSlot.heatResult;const finalRankDisplay=heatResultFromDB.finalRank>0?String(heatResultFromDB.finalRank):(heatResultFromDB.specialStatus||'-');const hasRollZone=this.param.rollZoneAfterGate!==-1;const penaltyLen=this.param.gateCount+(hasRollZone?2:1);serieInstance.slots[slotIndex]={participant:participant||catInstance.placeholderParticipant,prioDepart:persistedSlot.prioDepart,heatResult:{order:heatResultFromDB.order?String(heatResultFromDB.order):null,penalty:persistedSlot.heatResult.penalty||"0".repeat(penaltyLen),specialStatus:persistedSlot.heatResult.specialStatus,finalRank:finalRankDisplay}};}});if(persistedHeat.etat===HeatState.OFFICIEL){serieInstance.etat=HeatState.OFFICIEL;serieInstance.slots.forEach(slot=>{if(slot.participant&&slot.participant.rankTT>0&&slot.participant.addHeatResultToHistory){slot.participant.addHeatResultToHistory(serieInstance.roundKey,serieInstance.name,slot.prioDepart,slot.heatResult.order,slot.heatResult.penalty,slot.heatResult.finalRank);}});}
currentRound.heats.push(serieInstance);}
catInstance.rounds[roundKey]=currentRound;}
catInstance.generateAndStoreFinalRanking();newCategoriesData[catKey]=catInstance;}
const sortedCategories=Object.values(newCategoriesData).sort((a,b)=>a.ordre-b.ordre);this.param.categoriesData=Object.fromEntries(sortedCategories.map(cat=>[cat.cle,cat]));this._calculateGlobalHeatNumbers();this.param.isConfigurationValidated=true;this.param.liveWebConfig=liveWebConfig;this.param.hasClub=Object.values(this.param.categoriesData).some(c=>c.hasClub);this.param.hasSexe=Object.values(this.param.categoriesData).some(c=>c.hasSexe);this.param.hasNation=Object.values(this.param.categoriesData).some(c=>c.hasNation);}
async chargerDonneesCompetitionDepuisURL(competitionCode){try{const source=String(competitionCode).match(/^[MI]/)?'manual':'competffck';const apiUrl=`./api/api_competffck_resultats.php?competition=${competitionCode}&source=${source}`;const response=await fetch(apiUrl);if(!response.ok)throw new Error(`Erreur HTTP: ${response.status}`);const apiResults=await response.json();if(!apiResults.success)throw new Error(apiResults.message||"Données API invalides.");const cleanCategoryKey=(key)=>key.replace(/I(.)$/i,'$1');if(apiResults.data){if(apiResults.data.statuts_categories){const newStatuts={};for(const key in apiResults.data.statuts_categories){newStatuts[cleanCategoryKey(key)]=apiResults.data.statuts_categories[key];}
apiResults.data.statuts_categories=newStatuts;}
if(apiResults.data.resultats_par_categorie){const newResultats={};for(const key in apiResults.data.resultats_par_categorie){const cleanedKey=cleanCategoryKey(key);const participants=apiResults.data.resultats_par_categorie[key];participants.forEach(p=>{if(p.Code_categorie)p.Code_categorie=cleanedKey;});newResultats[cleanedKey]=participants;}
apiResults.data.resultats_par_categorie=newResultats;}}
this.param.apiResultsData=apiResults.data;this.param.selectedCompetitionAPIInfo=this.param.apiResultsData.competition_details;this._notifySubscribers();}catch(error){console.error("Erreur chargement compétition:",error);}}
selectionnerFormatDeRegles(formatKey,formatsDisponibles){this.param.formatCompetitionActifPourRegles=formatsDisponibles[formatKey]||null;this._notifySubscribers();}
async validerConfigurationCategoriesEtDemarrerApp(configOptions){const{formatKey,gateCount,gateProfil,rollZoneAfterGate,categorySelections}=configOptions;if(!this.param.formatCompetitionActifPourRegles){notifyError("Veuillez sélectionner un format de règles avant de démarrer.");return;}
const hasActiveCategories=categorySelections.some(sel=>sel.nomVariante!=="0");if(!hasActiveCategories){if(this.param.isConfigurationValidated){this.param.isConfigurationValidated=false;this.param.categoriesData={};this.param.schedulesData={};this._notifySubscribers();notifyError("Toutes les catégories ont été désactivées. L'application est réinitialisée.");}else{notifyError("Veuillez configurer au moins une catégorie avec des participants.");}
return;}
this.param.gateCount=gateCount;this.param.rollZoneAfterGate=isNaN(rollZoneAfterGate)?0:rollZoneAfterGate;this.param.gateProfil=gateProfil||"0".repeat(gateCount);const activeCategoryKeys=new Set();for(const selection of categorySelections){const{catKey,nomVariante,ordre}=selection;if(!catKey||nomVariante==="0")continue;const configVariante=this.param.formatCompetitionActifPourRegles.variantesParNbParticipants[nomVariante];if(!configVariante){notifyError(`Configuration de variante "${nomVariante}" introuvable pour la catégorie ${catKey}.`);continue;}
activeCategoryKeys.add(catKey);const categorieExistante=this.param.categoriesData[catKey];if(categorieExistante&&categorieExistante.nomVariante===nomVariante){categorieExistante.ordre=ordre;}else{let nomLongCat=this.param.apiResultsData?.statuts_categories?.[catKey]?.Nom_categorie||catKey,nomCourtCat=catKey;const nouvelleCategorieInstance=new CategorieCompetition(catKey,nomLongCat,nomCourtCat,configVariante.nb_participants,configVariante,nomVariante,ordre,this.param.formatCompetitionActifPourRegles.schemasCommuns);if(categorieExistante&&categorieExistante.masterParticipantList.length>0){nouvelleCategorieInstance.masterParticipantList=categorieExistante.masterParticipantList;}else if(this.param.apiResultsData?.resultats_par_categorie[catKey]){nouvelleCategorieInstance.buildMasterListFromAPIData(this.param.apiResultsData.resultats_par_categorie[catKey]);}
nouvelleCategorieInstance.initializeRoundsAndSeed();this.param.categoriesData[catKey]=nouvelleCategorieInstance;}}
for(const existingCatKey in this.param.categoriesData){if(!activeCategoryKeys.has(existingCatKey)){delete this.param.categoriesData[existingCatKey];}}
const sortedActiveCategories=Object.values(this.param.categoriesData).sort((a,b)=>a.ordre-b.ordre);this.param.categoriesData=Object.fromEntries(sortedActiveCategories.map(cat=>[cat.cle,cat]));this.param.hasClub=Object.values(this.param.categoriesData).some(c=>c.hasClub);this.param.hasSexe=Object.values(this.param.categoriesData).some(c=>c.hasSexe);this.param.hasNation=Object.values(this.param.categoriesData).some(c=>c.hasNation);this.param.isConfigurationValidated=true;this.initialiserDonneesHoraires();this.updateAllHeatsState();if(this.persistenceManager){try{const result=await this.persistenceManager.saveFullConfiguration({formatKey:formatKey,gateCount:this.param.gateCount,gateProfil:this.param.gateProfil,rollZoneAfterGate:this.param.rollZoneAfterGate,globalScheduleSettings:this.param.globalScheduleSettings,categoriesData:this.param.categoriesData,schedulesData:this.param.schedulesData})
if(result&&result.idMapping&&result.idMapping.heats){this.updateHeatsWithDBIds(result.idMapping.heats);}}catch(err){notifyError(`Erreur de sauvegarde: ${err.message}`)};}
this._notifySubscribers();}
initialiserDonneesHoraires(){const anciensHoraires={...this.param.schedulesData};this.param.schedulesData={};const phasesActives={};for(const catKey in this.param.categoriesData){const catInstance=this.param.categoriesData[catKey];if(catInstance.configVariante&&catInstance.configVariante.phases){catInstance.configVariante.phases.forEach(phaseConfig=>{if(!phasesActives[phaseConfig.cle]){phasesActives[phaseConfig.cle]={name:phaseConfig.nom,categories:[]};}
if(catInstance.rounds[phaseConfig.cle]?.heats.length>0){if(!phasesActives[phaseConfig.cle].categories.includes(catKey)){phasesActives[phaseConfig.cle].categories.push(catKey);}}});}}
for(const phaseKey in phasesActives){phasesActives[phaseKey].categories.sort((catKeyA,catKeyB)=>{const catA=this.param.categoriesData[catKeyA];const catB=this.param.categoriesData[catKeyB];if(!catA||!catB)return 0;return catA.ordre-catB.ordre;});const categoriesOrder=anciensHoraires[phaseKey]?anciensHoraires[phaseKey].categoriesOrder.filter(cat=>phasesActives[phaseKey].categories.includes(cat)):phasesActives[phaseKey].categories;phasesActives[phaseKey].categories.forEach(cat=>{if(!categoriesOrder.includes(cat))categoriesOrder.push(cat);});this.param.schedulesData[phaseKey]={phaseName:phasesActives[phaseKey].name,categoriesOrder:categoriesOrder,categoriesDetails:{}};categoriesOrder.forEach(catKey=>{const catInstance=this.param.categoriesData[catKey];const nbSeries=catInstance.rounds[phaseKey]?.heats.length||0;const anciensDetails=anciensHoraires[phaseKey]?.categoriesDetails[catKey];this.param.schedulesData[phaseKey].categoriesDetails[catKey]={name:catInstance.nomCourt,nbSeries:nbSeries,ecartSeriesOverride:anciensDetails?anciensDetails.ecartSeriesOverride:null,ecartApresCategorieOverride:anciensDetails?anciensDetails.ecartApresCategorieOverride:null,startTime:anciensDetails?anciensDetails.startTime:null,isStartTimeUserFixed:anciensDetails?anciensDetails.isStartTimeUserFixed:false,lastHeatStartTime:anciensDetails?anciensDetails.lastHeatStartTime:null};});this.recalculateSchedulesForPhase(phaseKey);}
this._calculateGlobalHeatNumbers();}
recalculateSchedulesForPhase(phaseKey){const phaseData=this.param.schedulesData[phaseKey];if(!phaseData)return;let previousCategoryLastHeatStartTimeInSeconds=null;let firstCategoryWithStartTimeFound=false;for(const catKey of phaseData.categoriesOrder){const catDetails=phaseData.categoriesDetails[catKey];const categorieInstance=this.param.categoriesData[catKey];const seriesDeLaCategorieDansPhase=categorieInstance?.rounds[phaseKey]?.heats;if(!catDetails)continue;if(catDetails.nbSeries===0){catDetails.startTime=null;catDetails.lastHeatStartTime=null;catDetails.isStartTimeUserFixed=false;if(seriesDeLaCategorieDansPhase)seriesDeLaCategorieDansPhase.forEach(s=>s.startTime="");continue;}
const ecartSeriesToUse=(catDetails.ecartSeriesOverride!==null?catDetails.ecartSeriesOverride:this.param.globalScheduleSettings.defaultEcartSeriesGlobal);let currentCatStartTimeInSeconds=null;if(catDetails.isStartTimeUserFixed&&catDetails.startTime){currentCatStartTimeInSeconds=timeToSeconds(catDetails.startTime);firstCategoryWithStartTimeFound=true;}else if(firstCategoryWithStartTimeFound&&previousCategoryLastHeatStartTimeInSeconds!==null){const indexCourant=phaseData.categoriesOrder.indexOf(catKey);let ecartApresCatPrecedente=this.param.globalScheduleSettings.defaultEcartCategoriesGlobal;if(indexCourant>0){const prevCatKey=phaseData.categoriesOrder[indexCourant-1];const prevCatDetails=phaseData.categoriesDetails[prevCatKey];if(prevCatDetails&&prevCatDetails.ecartApresCategorieOverride!==null){ecartApresCatPrecedente=prevCatDetails.ecartApresCategorieOverride;}}
currentCatStartTimeInSeconds=previousCategoryLastHeatStartTimeInSeconds+ecartApresCatPrecedente;catDetails.startTime=secondsToTime(currentCatStartTimeInSeconds);catDetails.isStartTimeUserFixed=false;}else if(!firstCategoryWithStartTimeFound&&catDetails.startTime){currentCatStartTimeInSeconds=timeToSeconds(catDetails.startTime);if(currentCatStartTimeInSeconds!==null){firstCategoryWithStartTimeFound=true;}else{catDetails.startTime=null;catDetails.isStartTimeUserFixed=false;}}else{catDetails.startTime=null;catDetails.isStartTimeUserFixed=false;}
if(currentCatStartTimeInSeconds!==null){catDetails.lastHeatStartTime=secondsToTime(currentCatStartTimeInSeconds+(catDetails.nbSeries-1)*ecartSeriesToUse);previousCategoryLastHeatStartTimeInSeconds=timeToSeconds(catDetails.lastHeatStartTime);if(seriesDeLaCategorieDansPhase){let heureSerieCouranteEnSecondes=currentCatStartTimeInSeconds;seriesDeLaCategorieDansPhase.forEach((serieInstance)=>{serieInstance.startTime=secondsToTime(heureSerieCouranteEnSecondes);heureSerieCouranteEnSecondes+=ecartSeriesToUse;});}}else{catDetails.lastHeatStartTime=null;previousCategoryLastHeatStartTimeInSeconds=null;if(seriesDeLaCategorieDansPhase)seriesDeLaCategorieDansPhase.forEach(s=>s.startTime="");}}}
updateGlobalDefaultEcartSeries(value){const val=parseInt(value,10)*60;if(!isNaN(val)&&val>=0){this.param.globalScheduleSettings.defaultEcartSeriesGlobal=val;Object.keys(this.param.schedulesData).forEach(phaseKey=>{this.recalculateSchedulesForPhase(phaseKey);});this._calculateGlobalHeatNumbers();if(this.persistenceManager){this.persistenceManager.updateGlobalSettingsSchedule(this.param.globalScheduleSettings).catch(err=>notifyError(`Erreur de sauvegarde des paramètres globaux: ${err.message}`));this.persistenceManager.saveSchedules({schedulesData:this.param.schedulesData,categoriesData:this.param.categoriesData}).catch(err=>notifyError(`Erreur de sauvegarde des horaires: ${err.message}`));}
this._notifySubscribers();}}
updateGlobalDefaultEcartCategories(value){const val=parseInt(value,10)*60;if(!isNaN(val)&&val>=0){this.param.globalScheduleSettings.defaultEcartCategoriesGlobal=val;Object.keys(this.param.schedulesData).forEach(phaseKey=>{this.recalculateSchedulesForPhase(phaseKey);});this._calculateGlobalHeatNumbers();if(this.persistenceManager){this.persistenceManager.updateGlobalSettingsSchedule(this.param.globalScheduleSettings).catch(err=>notifyError(`Erreur de sauvegarde des paramètres globaux: ${err.message}`));this.persistenceManager.saveSchedules({schedulesData:this.param.schedulesData,categoriesData:this.param.categoriesData}).catch(err=>notifyError(`Erreur de sauvegarde des horaires: ${err.message}`));}
this._notifySubscribers();}}
updateCategoryStartTime(phaseKey,catKey,timeValue){const phaseData=this.param.schedulesData[phaseKey];if(phaseData&&phaseData.categoriesDetails[catKey]){if(timeValue&&timeValue!==""){phaseData.categoriesDetails[catKey].startTime=timeValue;phaseData.categoriesDetails[catKey].isStartTimeUserFixed=true;}else{phaseData.categoriesDetails[catKey].startTime=null;phaseData.categoriesDetails[catKey].isStartTimeUserFixed=false;}
this.recalculateSchedulesForPhase(phaseKey);this._calculateGlobalHeatNumbers();if(this.persistenceManager){this.persistenceManager.saveSchedules({schedulesData:this.param.schedulesData,categoriesData:this.param.categoriesData}).catch(err=>notifyError(`Erreur de sauvegarde des horaires: ${err.message}`));}
this._notifySubscribers();}}
updateCategoryEcartSeriesOverride(phaseKey,catKey,value){const val=value===""?null:parseInt(value,10)*60;const phaseData=this.param.schedulesData[phaseKey];if(phaseData&&phaseData.categoriesDetails[catKey]&&(val===null||(!isNaN(val)&&val>=0))){phaseData.categoriesDetails[catKey].ecartSeriesOverride=val;this.recalculateSchedulesForPhase(phaseKey);this._calculateGlobalHeatNumbers();if(this.persistenceManager){this.persistenceManager.saveSchedules({schedulesData:this.param.schedulesData,categoriesData:this.param.categoriesData}).catch(err=>notifyError(`Erreur de sauvegarde des horaires: ${err.message}`));}
this._notifySubscribers();}}
updateCategoryEcartApresCategorieOverride(phaseKey,catKey,value){const val=value===""?null:parseInt(value,10)*60;const phaseData=this.param.schedulesData[phaseKey];if(phaseData&&phaseData.categoriesDetails[catKey]&&(val===null||(!isNaN(val)&&val>=0))){phaseData.categoriesDetails[catKey].ecartApresCategorieOverride=val;this.recalculateSchedulesForPhase(phaseKey);this._calculateGlobalHeatNumbers();if(this.persistenceManager){this.persistenceManager.saveSchedules({schedulesData:this.param.schedulesData,categoriesData:this.param.categoriesData}).catch(err=>notifyError(`Erreur de sauvegarde des horaires: ${err.message}`));}
this._notifySubscribers();}}
changeCategoryOrderInPhase(phaseKey,catKey,direction){const phaseData=this.param.schedulesData[phaseKey];if(!phaseData)return;const index=phaseData.categoriesOrder.indexOf(catKey);if(index===-1)return;if(direction==='up'&&index>0){[phaseData.categoriesOrder[index],phaseData.categoriesOrder[index-1]]=[phaseData.categoriesOrder[index-1],phaseData.categoriesOrder[index]];}else if(direction==='down'&&index<phaseData.categoriesOrder.length-1){[phaseData.categoriesOrder[index],phaseData.categoriesOrder[index+1]]=[phaseData.categoriesOrder[index+1],phaseData.categoriesOrder[index]];}else{return;}
this.recalculateSchedulesForPhase(phaseKey);this._calculateGlobalHeatNumbers();if(this.persistenceManager){this.persistenceManager.saveSchedules({schedulesData:this.param.schedulesData,categoriesData:this.param.categoriesData}).catch(err=>notifyError(`Erreur de sauvegarde des horaires: ${err.message}`));}
this._notifySubscribers();}
gererChangementResultat(event){const{category,round,heatindex,competitorindex}=event.target.dataset;const value=event.target.value;const type=event.target.classList.contains('result-select')?'order':'status';const categorieInstance=this.param.categoriesData[category];const serieInstance=categorieInstance?.getSerie(round,parseInt(heatindex,10));if(serieInstance){const slot=serieInstance.slots[parseInt(competitorindex,10)];if(!slot)return;if(type==='order'){slot.heatResult.order=(value==="")?null:value;if(value!==""){slot.heatResult.specialStatus=null;}}else if(type==='status'){slot.heatResult.specialStatus=(value==="")?null:value;if(value!==""){slot.heatResult.order=null;}}
serieInstance.calculateAndApplyRanking();this._notifyHeatUpdated(category,round,parseInt(heatindex,10));}}
async gererValidationClassement(event){const button=event.target;const{category,round,heatindex}=button.dataset;const categorieInstance=this.param.categoriesData[category];const serieInstance=categorieInstance?.getSerie(round,parseInt(heatindex,10));if(!serieInstance){return{success:false,errorCode:'HEAT_NOT_FOUND'};}
if(serieInstance.etat===HeatState.EN_ATTENTE){return{success:false,errorCode:'VALIDATION_ON_PENDING_HEAT'};}
if(serieInstance.etat===HeatState.OFFICIEL){const targetHeats=[];const progressionConfig=categorieInstance.configVariante.progressions.find(p=>p.phaseSourceCle===round);if(progressionConfig){let reglesProgressionApplicables=progressionConfig.regles||categorieInstance._schemasCommunsGlobaux[progressionConfig.refSchemaCommun]?.regles;if(reglesProgressionApplicables){reglesProgressionApplicables.forEach(regleSerieCible=>{regleSerieCible.groupesDeSeeding.forEach(groupe=>{if(groupe.sources.some(s=>s.serieSourceIndex===parseInt(heatindex,10))){const targetHeat=categorieInstance.rounds[progressionConfig.phaseCibleCle]?.heats[regleSerieCible.serieCibleIndex];if(targetHeat&&!targetHeats.includes(targetHeat)){targetHeats.push(targetHeat);}}});});}}
const isAnyTargetHeatValidated=targetHeats.some(heat=>heat.etat===HeatState.OFFICIEL);if(isAnyTargetHeatValidated){return{success:false,errorCode:'DEVALIDATION_BLOCKED_BY_NEXT_HEATS'}}
serieInstance.etat=HeatState.EN_MODIF;this._notifySubscribers();return{success:true,action:'devalidated'};}
if(!serieInstance.areAllActiveResultsEntered()){return{success:false,errorCode:'INCOMPLETE_RESULTS'};}
serieInstance.slots.forEach(slot=>{if(slot.participant&&slot.participant.rankTT>0)
if(slot.heatResult.penalty===null)
slot.heatResult.penalty='0'.repeat(this.param.gateCount+2);})
serieInstance.RankingValidated();serieInstance.etat=HeatState.OFFICIEL;const modifiedTargetHeats=this._reevaluerEtAppliquerToutesLesProgressions(categorieInstance);this.updateAllHeatsState();categorieInstance.generateAndStoreFinalRanking();if(this.persistenceManager){try{const sourceHeatData={...serieInstance,categoryKey:category,roundKey:round};const targetHeatsData=Array.from(modifiedTargetHeats).filter(h=>h.id!==null).map(h=>({...h,categoryKey:category,roundKey:h.roundKey}));await this.persistenceManager.saveProgression(sourceHeatData,targetHeatsData,categorieInstance.finalRanking);}catch(err){console.error("Erreur de sauvegarde dans le moteur:",err);return{success:false,errorCode:'SAVE_FAILED',details:{message:err.message}};}}
this._notifySubscribers();return{success:true,action:'validated'}}
_reevaluerEtAppliquerToutesLesProgressions(catInstance){const modifiedHeats=new Set();if(!catInstance.configVariante?.progressions){return modifiedHeats;}
const config=catInstance.configVariante;const schemasCommuns=catInstance._schemasCommunsGlobaux||{};config.progressions.forEach(progRule=>{let reglesProgressionApplicables=progRule.regles||(schemasCommuns[progRule.refSchemaCommun]?schemasCommuns[progRule.refSchemaCommun].regles:null);if(!reglesProgressionApplicables)return;reglesProgressionApplicables.forEach(regleSerieCible=>{const serieCible=catInstance.rounds[progRule.phaseCibleCle]?.heats[regleSerieCible.serieCibleIndex];if(!serieCible||serieCible.etat===HeatState.OFFICIEL){return;}
regleSerieCible.groupesDeSeeding.forEach(groupe=>{const participantsCandidats=[];let toutesSourcesValidees=true;groupe.sources.forEach(sourceInfo=>{const serieSource=catInstance.rounds[progRule.phaseSourceCle]?.heats[sourceInfo.serieSourceIndex];if(!serieSource||serieSource.etat!==HeatState.OFFICIEL){toutesSourcesValidees=false;return;}
const slotQualifie=serieSource.slots.find(s=>parseInt(s.heatResult.finalRank,10)===sourceInfo.rangDansSerieSource);const hResult=slotQualifie?.heatResult;const p=slotQualifie?.participant;const status=hResult?.specialStatus;const isExcluded=ConfigurationPenalites.PENALTIES_EXCLUDING_PROGRESSION.has(status)
if(p&&p.rankTT>0&&!isExcluded){participantsCandidats.push(p);}else{participantsCandidats.push(catInstance.placeholderParticipant);}});if(toutesSourcesValidees){participantsCandidats.sort((a,b)=>{const valA=a.rankTT>0?a.rankTT:Infinity;const valB=b.rankTT>0?b.rankTT:Infinity;return valA-valB;});groupe.slotsCibles.forEach((slotCibleIndex,i)=>{const participantAssigne=participantsCandidats[i]||catInstance.placeholderParticipant;const slotCible=serieCible.slots[slotCibleIndex];if(slotCible){const ancienParticipantId=slotCible.participant?slotCible.participant.id:null;if(ancienParticipantId!==participantAssigne.id){slotCible.participant=participantAssigne;slotCible.heatResult={order:null,penalty:null,specialStatus:null,finalRank:'-'};slotCible.prioDepart=slotCibleIndex+1;modifiedHeats.add(serieCible);}}});}});});});return modifiedHeats;}
_reevaluerEtAppliquerProgressions(catInstance){const modifiedHeats=this._reevaluerEtAppliquerToutesLesProgressions(catInstance);return modifiedHeats;}}
export{ApplicationCourse,ConfigurationPenalites,CategorieCompetition,Serie,PenaltyEncoder,Participant};