import{applyStaticTexts}from'./utils.js';import{loadLanguage}from'./languageManager.js';import{LanguageSelector}from'./languageSelector.js';import{appInfo}from'../appInfo.js';import{ImportExportManager}from'./import_export.js';function parseFrenchDate(dateStr){if(!dateStr)return new Date(0);const[day,month,year]=dateStr.split('/');return new Date(year,month-1,day);}
let currentSort={field:'date',order:'asc'};let allCompetitionsData=[];document.addEventListener('DOMContentLoaded',async()=>{await loadLanguage(['index']);applyStaticTexts(window.APP_TEXTS,document.body);const languageSelector=new LanguageSelector('language-selector-container');languageSelector.init();const versionSpan=document.getElementById('header-version');if(versionSpan){versionSpan.textContent=`v${appInfo.version}`;}
const aboutBtn=document.getElementById('btn-about');const aboutModal=document.getElementById('about-modal');const closeAboutBtn=document.getElementById('close-about-btn');if(aboutBtn&&aboutModal){document.getElementById('about-app-name').textContent=appInfo.fullName;document.getElementById('about-version').textContent=appInfo.version;document.getElementById('about-date').textContent=appInfo.date;document.getElementById('about-author').textContent=appInfo.autor;aboutBtn.addEventListener('click',()=>{aboutModal.style.display='flex';setTimeout(()=>aboutModal.classList.add('visible'),10);});closeAboutBtn.addEventListener('click',()=>{aboutModal.classList.remove('visible');setTimeout(()=>aboutModal.style.display='none',300);});aboutModal.addEventListener('click',(e)=>{if(e.target===aboutModal){aboutModal.classList.remove('visible');setTimeout(()=>aboutModal.style.display='none',300);}});}
const importationContainer=document.getElementById('importation-container');const competitionsContainer=document.getElementById('competitions-container');const noCompetitionsPanel=document.getElementById('no-competitions');const setupPanel=document.getElementById('setup-container');const createTablesBtn=document.getElementById('create-tables-btn');const setupMessage=document.getElementById('setup-message');try{const updateResponse=await fetch('./api/api_create_tables.php?mode=auto');const updateResult=await updateResponse.json();if(updateResult.success&&updateResult.report&&updateResult.report.length>0){console.log("Mise à jour automatique de la BDD :",updateResult.report);}}catch(e){console.warn("Impossible de vérifier les mises à jour auto de la BDD (ceci est normal si l'installation n'est pas faite) :",e);}
function showCustomConfirm(title,message,buttons){return new Promise((resolve)=>{const overlay=document.getElementById('custom-dialog-overlay');const titleEl=overlay.querySelector('#dialog-title');const messageEl=overlay.querySelector('#dialog-message');const actionsEl=overlay.querySelector('#dialog-actions');titleEl.textContent=title;messageEl.innerHTML=message;actionsEl.innerHTML='';buttons.forEach(btnInfo=>{const button=document.createElement('button');button.textContent=btnInfo.text;button.dataset.value=btnInfo.value;if(btnInfo.class)button.classList.add(btnInfo.class);actionsEl.appendChild(button);});const clickHandler=(event)=>{const clickedButton=event.target.closest('button');if(clickedButton){overlay.style.display='none';actionsEl.removeEventListener('click',clickHandler);resolve(clickedButton.dataset.value);}};actionsEl.addEventListener('click',clickHandler);overlay.style.display='flex';});}
fetch('./api/api_test_tables.php').then(response=>{if(!response.ok){throw new Error(`HTTP error! status: ${response.status}`);}
return response.json();}).then(data=>{if(data.tables_exist){loadAllCompetitions();}else{importationContainer.style.display='none';competitionsContainer.style.display='none';noCompetitionsPanel.style.display='none';setupPanel.style.display='block';}}).catch(error=>{console.error(window.APP_TEXTS.indexPage.createError,error);displayError(setupPanel,window.APP_TEXTS.indexPage.tableError);});const ioManager=new ImportExportManager('CREATE_NEW');const btnImportMdv=document.getElementById('btn-import-mdv');const hiddenImportMdv=document.getElementById('hidden-import-mdv');if(btnImportMdv&&hiddenImportMdv){btnImportMdv.addEventListener('click',()=>hiddenImportMdv.click());hiddenImportMdv.addEventListener('change',async(e)=>{const file=e.target.files[0];if(!file)return;try{const{data}=await ioManager.parseImportFile(file);const stats=data.stats||{};const participantsCount=stats.participants||stats.manual_results||0;const t=window.APP_TEXTS.indexPage||{};const title=t.cloneTitle||"Clonage de course";const msg=(t.cloneMessage||`Vous allez créer une nouvelle course autonome à partir de ce fichier.<br><br><strong>Contenu :</strong><br>- Compétiteurs : {part}<br>- Séries : {series}<br><br>Continuer ?`).replace('{part}',participantsCount).replace('{series}',stats.series||0);const choice=await showCustomConfirm(title,msg,[{text:t.btnCancel||'Annuler',value:'cancel',class:'secondary'},{text:t.btnCreateCourse||'Créer la course',value:'confirm',class:'primary'}]);if(choice==='confirm'){btnImportMdv.innerHTML=`<span class="material-icons spinning">sync</span> <span data-i18n="import_export.creating">${t.creating || 'Création...'}</span>`;btnImportMdv.disabled=true;const result=await ioManager.executeImport(data);if(result.target_code){const lang=new URLSearchParams(window.location.search).get('lang');let targetUrl=`./admin.html?competition=${result.target_code}`;if(lang)targetUrl+=`&lang=${lang}`;window.location.href=targetUrl;}else{window.location.reload();}}}catch(err){await showCustomConfirm(window.APP_TEXTS.errorGeneric||"Erreur",err.message,[{text:'OK',value:'ok',class:'danger'}]);}finally{hiddenImportMdv.value='';const btnText=window.APP_TEXTS.indexPage?.importMdvButton||'Importer Archive (.mdv)';btnImportMdv.innerHTML=`<span class="material-icons">file_download</span> <span data-i18n="indexPage.importMdvButton">${btnText}</span>`;btnImportMdv.disabled=false;}});}
createTablesBtn.addEventListener('click',()=>{createTablesBtn.disabled=true;createTablesBtn.textContent=window.APP_TEXTS.indexPage.createTable;setupMessage.textContent='';setupMessage.className='';fetch('./api/api_create_tables.php').then(response=>response.json()).then(data=>{if(data.success){setupMessage.textContent=window.APP_TEXTS.indexPage.wait;setupMessage.className='message-success';setTimeout(()=>{window.location.reload();},1000);}else{throw new Error(data.message||window.APP_TEXTS.indexPage.unknownError);}}).catch(error=>{console.error(window.APP_TEXTS.indexPage.createError,error);setupMessage.textContent=window.APP_TEXTS.indexPage.errorTitle+' : '+error.message;setupMessage.className='message-error';createTablesBtn.disabled=false;createTablesBtn.textContent=window.APP_TEXTS.indexPage.createTablesBtn;});});const manualModal=document.getElementById('create-manual-modal');const manualForm=document.getElementById('create-manual-form');const csvFileInput=document.getElementById('csv-file-input');const csvMappingArea=document.getElementById('csv-mapping-area');const csvColumnMappers=document.getElementById('csv-column-mappers');const csvPreviewTable=document.getElementById('csv-preview-table');const processBtn=document.getElementById('process-manual-creation-btn');let parsedCsvData=null;document.getElementById('show-create-competition-modal-btn').addEventListener('click',()=>{manualForm.reset();csvMappingArea.style.display='none';processBtn.disabled=true;parsedCsvData=null;document.getElementById('csv-file-name').textContent=window.APP_TEXTS.indexPage.noFileSelected;manualModal.style.display='flex';});document.getElementById('cancel-manual-creation-btn').addEventListener('click',()=>{manualModal.style.display='none';});const dateDebutInput=document.getElementById('comp-date-debut');const dateFinInput=document.getElementById('comp-date-fin');dateDebutInput.addEventListener('change',()=>{if(!dateFinInput.value||dateFinInput.value<dateDebutInput.value){dateFinInput.value=dateDebutInput.value;}});csvFileInput.addEventListener('change',()=>{const file=csvFileInput.files[0];const fileNameDisplay=document.getElementById('csv-file-name');if(file){fileNameDisplay.textContent=file.name;}else{fileNameDisplay.textContent=window.APP_TEXTS.indexPage.noFileSelected;}
if(!file){csvMappingArea.style.display='none';processBtn.disabled=true;return;}
Papa.parse(file,{header:true,skipEmptyLines:true,preview:5,complete:(results)=>{parsedCsvData=results;const headers=results.meta.fields;displayCsvMappingUI(headers,results.data);}});});function checkFormValidity(){const isFormValid=manualForm.checkValidity();const isFileSelected=csvFileInput.files.length>0;processBtn.disabled=!(isFormValid&&isFileSelected);}
manualForm.querySelectorAll('input').forEach(input=>{input.addEventListener('input',checkFormValidity);});function findBestHeaderMatch(requiredFieldKey,headers){const lowerCaseHeaders=headers.map(h=>h.toLowerCase().trim());const synonyms=window.APP_TEXTS.indexPage.synonyms;const possibleNames=synonyms[requiredFieldKey]||[requiredFieldKey.toLowerCase()];for(const name of possibleNames){const index=lowerCaseHeaders.indexOf(name);if(index!==-1){return headers[index];}}
for(const name of possibleNames){for(let i=0;i<lowerCaseHeaders.length;i++){if(lowerCaseHeaders[i].includes(name)){return headers[i];}}}
return null;}
function displayCsvMappingUI(headers,previewData){const requiredFields=window.APP_TEXTS.indexPage.requiredFields;const mappersHtml=requiredFields.map(field=>{const selectorId=`map-${field.key}`;const bestMatch=findBestHeaderMatch(field.key,headers);let options='<option value="">-- Ignorer --</option>';headers.forEach(header=>{const isSelected=(header===bestMatch)?'selected':'';options+=`<option value="${header}" ${isSelected}>${header}</option>`;});let label=field.label;if((field.key=="Cltc")||(field.key=="Tps_chrono"))label+=" (*)"
if((field.key=="Nom")||(field.key=="Code_categorie"))label+="*"
return`
                        <div style="margin-bottom: 5px;">
                            <label for="${selectorId}" style="display: inline-block; width: 200px;">${label}:</label>
                            <select id="${selectorId}" data-field-key="${field.key}">${options}</select>
                        </div>
                        `;}).join('');csvColumnMappers.innerHTML=mappersHtml;let table='<table><thead><tr>'+headers.map(h=>`<th>${h}</th>`).join('')+'</tr></thead><tbody>';previewData.forEach(row=>{table+='<tr>'+headers.map(h=>`<td>${row[h] || ''}</td>`).join('')+'</tr>';});table+='</tbody></table>';csvPreviewTable.innerHTML=table;csvMappingArea.style.display='block';checkFormValidity();}
manualForm.addEventListener('submit',async(e)=>{e.preventDefault();const mapping={};document.querySelectorAll('#csv-column-mappers select').forEach(select=>{if(select.value)mapping[select.dataset.fieldKey]=select.value;});if((!mapping.Cltc&&!mapping.Tps_chrono)||!mapping.Code_categorie||!mapping.Nom){await showCustomConfirm(window.APP_TEXTS.indexPage.errorTitle,window.APP_TEXTS.indexPage.errorMappingMessage,[{text:window.APP_TEXTS.indexPage.btnClose,value:'ok',class:'primary'}]);return;}
Papa.parse(csvFileInput.files[0],{header:true,skipEmptyLines:true,complete:async(fullResults)=>{processBtn.textContent=window.APP_TEXTS.indexPage.btnCreating;processBtn.disabled=true;const competitionDetails={nom:document.getElementById('comp-nom').value,ville:document.getElementById('comp-ville').value,date_debut:document.getElementById('comp-date-debut').value,date_fin:document.getElementById('comp-date-fin').value};try{const response=await fetch('./api/api_create_and_import_manual.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({competitionDetails:competitionDetails,mapping:mapping,data:fullResults.data})});const result=await response.json();if(!response.ok||!result.success){let displayMessage;if(result.error&&result.error.key){const errorTemplates=window.APP_TEXTS.indexPage.apiErrors||{};let template=errorTemplates[result.error.key];if(template){displayMessage=template.replace(/{(\w+)}/g,(match,key)=>{return result.error.params&&result.error.params[key]!==undefined?result.error.params[key]:match;});}else{displayMessage=`Erreur inconnue de l'API : ${result.error.key}`;}}else{displayMessage=result.message||window.APP_TEXTS.indexPage.unknownError;}
await showCustomConfirm(window.APP_TEXTS.indexPage.errorTitle,displayMessage,[{text:window.APP_TEXTS.indexPage.btnClose,value:'ok',class:'primary'}]);processBtn.textContent=window.APP_TEXTS.indexPage.btnCreateAndImport;checkFormValidity();return;}
const lang=new URLSearchParams(window.location.search).get('lang');let targetUrl=`./admin.html?competition=${result.competitionCode}`;if(lang)targetUrl+=`&lang=${lang}`;window.location.href=targetUrl;}catch(networkError){await showCustomConfirm(window.APP_TEXTS.indexPage.errorTitle,`Erreur de communication avec le serveur : ${networkError.message}`,[{text:window.APP_TEXTS.indexPage.btnClose,value:'ok',class:'primary'}]);processBtn.textContent=window.APP_TEXTS.indexPage.btnCreateAndImport;checkFormValidity();}}});});function sortCompetitions(competitions,field,order){return[...competitions].sort((a,b)=>{let valA,valB;if(field==='date'){valA=parseFrenchDate(a.Date_debut);valB=parseFrenchDate(b.Date_debut);if(valA.getTime()===valB.getTime()){let codeA=parseInt(String(a.Code).replace(/[^0-9]/g,''),10)||0;let codeB=parseInt(String(b.Code).replace(/[^0-9]/g,''),10)||0;return order==='asc'?codeA-codeB:codeB-codeA;}}else if(field==='code'){valA=parseInt(String(a.Code).replace(/[^0-9]/g,''),10)||0;valB=parseInt(String(b.Code).replace(/[^0-9]/g,''),10)||0;}
const comparison=valA-valB;return order==='asc'?comparison:-comparison;});}
function updateSortButtons(){document.querySelectorAll('.sort-btn').forEach(btn=>{const isActive=btn.dataset.sort===currentSort.field;btn.classList.toggle('active',isActive);const icon=btn.querySelector('.sort-icon');if(isActive){icon.textContent=currentSort.order==='asc'?'▲':'▼';}else{icon.textContent='▼';}});}
function renderCompetitionsList(competitions){const lang=new URLSearchParams(window.location.search).get('lang');competitionsContainer.innerHTML='';competitions.forEach(comp=>{const listItem=document.createElement('li');listItem.className='competition-list-item';let targetUrl=`admin.html?competition=${comp.Code}`;if(lang){targetUrl+=`&lang=${lang}`;}
listItem.dataset.url=targetUrl;const isManual=String(comp.Code).startsWith('M')||String(comp.Code).startsWith('I');let codeHtml='';let etatHtml='';codeHtml=`<span class="item-code">${comp.Code}</span>`;if(isManual){etatHtml=`<button class="delete-manual-comp-btn" data-comp-id="${comp.Code}" title="Supprimer" ><span  data-comp-id="${comp.Code}" class="material-icons delete-manual-comp-btn" >delete</span></button>`;}else{etatHtml=`<span class="etat-badge ${getEtatClass(comp.Etat)}">${comp.Etat ?? '-'}</span>`;}
listItem.innerHTML=`
                        ${codeHtml}
                        <span class="item-etat">${etatHtml}</span>
                        <span class="item-title">${comp.Nom}</span>
                        <span class="item-ville">${comp.Ville}</span>
                        <span class="item-date">${comp.Date_debut}${comp.Date_fin && comp.Date_debut !== comp.Date_fin ? ' - ' + comp.Date_fin : ''}</span>
                    `;competitionsContainer.appendChild(listItem);});}
function loadAllCompetitions(){const fetchCompetffck=fetch('./api/api_competffck_competitions.php').then(res=>res.json());const fetchManual=fetch('./api/api_get_manual_competitions.php').then(res=>res.json());Promise.all([fetchCompetffck,fetchManual]).then(([competffckData,manualResult])=>{const manualData=manualResult.success?manualResult.data:[];allCompetitionsData=[...competffckData,...manualData];if(allCompetitionsData.length===0){noCompetitionsPanel.style.display='block';competitionsContainer.style.display='none';document.getElementById('competitions-list-header').style.display='none';return;}
document.getElementById('competitions-list-header').style.display='flex';const sortedCompetitions=sortCompetitions(allCompetitionsData,currentSort.field,currentSort.order);renderCompetitionsList(sortedCompetitions);updateSortButtons();}).catch(error=>{console.error('Erreur API:',error);displayError(noCompetitionsPanel,window.APP_TEXTS.indexPage.competitionError);});}
document.getElementById('competitions-list-header').addEventListener('click',(e)=>{const btn=e.target.closest('.sort-btn');if(!btn)return;const field=btn.dataset.sort;if(currentSort.field===field){currentSort.order=currentSort.order==='asc'?'desc':'asc';}else{currentSort.field=field;currentSort.order='desc';}
updateSortButtons();renderCompetitionsList(sortCompetitions(allCompetitionsData,currentSort.field,currentSort.order));});competitionsContainer.addEventListener('click',async(e)=>{const deleteBtn=e.target.closest('.delete-manual-comp-btn');if(deleteBtn){e.stopPropagation();const compId=deleteBtn.dataset.compId;const message=window.APP_TEXTS.indexPage.confirmDeleteMessage.replace('{compId}',compId);const choice=await showCustomConfirm(window.APP_TEXTS.indexPage.confirmDeleteTitle,message,[{text:window.APP_TEXTS.indexPage.btnCancel,value:'cancel',class:'secondary'},{text:window.APP_TEXTS.indexPage.btnConfirm,value:'confirm',class:'danger'}]);if(choice==='confirm'){try{const response=await fetch('./api/api_delete_manual_competition.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({competitionCode:compId})});const result=await response.json();if(!result.success)throw new Error(result.message);loadAllCompetitions();}catch(error){console.log(error.message)
const errorMessage=window.APP_TEXTS.indexPage.errorDeletion.replace('{error}',error.message);await showCustomConfirm(window.APP_TEXTS.indexPage.errorTitle,errorMessage,[{text:window.APP_TEXTS.indexPage.btnClose,value:'ok',class:'primary'}]);}}}else{const listItem=e.target.closest('.competition-list-item');if(listItem){window.location.href=listItem.dataset.url;}}});function displayError(panelElement,message){competitionsContainer.style.display='none';noCompetitionsPanel.style.display='none';setupPanel.style.display='none';panelElement.style.display='block';panelElement.innerHTML=`<h3>${window.APP_TEXTS.indexPage.loadError}</h3><p>${message}</p>`;}
function getEtatClass(etatValue){const etatStr=String(etatValue);switch(etatStr){case'1':return'etat-val-1';case'2':return'etat-val-2';case'3':return'etat-val-3';case'4':return'etat-val-4';case'6':return'etat-val-6';default:return'etat-val-default';}}});