import{ConfigurationPenalites}from'./engine.js';export class PenaltyModal{constructor(modalId){this.modalOverlay=document.getElementById(modalId);if(!this.modalOverlay){throw new Error(`Élément modal non trouvé pour l'ID : ${modalId}`);}
this.titleEl=this.modalOverlay.querySelector('h2');this.headerEl=this.modalOverlay.querySelector('.penalty-grid-header');this.bodyEl=this.modalOverlay.querySelector('.penalty-grid, .global-penalty-grid-wrapper #global-penalty-modal-body');this.saveBtn=this.modalOverlay.querySelector('.primary');this.cancelBtn=this.modalOverlay.querySelector('.secondary');this.resolvePromise=null;this.rejectPromise=null;this.temporaryState=null;this.isGlobal=modalId.includes('global');this._attachEventListeners();}
open(config){return new Promise((resolve,reject)=>{this.resolvePromise=resolve;this.rejectPromise=reject;this._applyTexts(config.context||'default');this._buildUI(config);this.modalOverlay.classList.add('visible');});}
_applyTexts(context){const texts=window.APP_TEXTS.dialogpenalty;this.cancelBtn.textContent=texts.btnCancel;let saveButtonText='';if(context==='jugement'){saveButtonText=this.isGlobal?texts.btnValidateAll:texts.btnValidate;}else{saveButtonText=this.isGlobal?texts.btnSaveAll:texts.btnSave;}
this.saveBtn.textContent=saveButtonText;let titleText='';if(context==='jugement'){titleText=this.isGlobal?texts.globalPenaltyTitleJugement:texts.penaltyTitleJugement;}else{titleText=this.isGlobal?texts.globalPenaltyTitle:texts.penaltyTitle;}
this.titleEl.textContent=titleText;}
_buildUI(config){if(config.type==='individual'){this._buildIndividualUI(config);}else if(config.type==='global'){this._buildGlobalUI(config);}}
_buildIndividualUI(config){const{heat,competitorIndex,gateConfig}=config;const slot=heat.slots[competitorIndex];this.temporaryState=slot.heatResult.penalty||'0'.repeat(gateConfig.gateCount+2);this.titleEl.textContent=window.APP_TEXTS.dialogpenalty.penaltyTitleTemplate.replace('{name}',slot.participant.name).replace('{bib}',slot.participant.bib);const zones=ConfigurationPenalites.genererSequenceZones(gateConfig.gateCount,gateConfig.rollZoneAfterGate);const penalties=this.temporaryState.split('');this.headerEl.innerHTML='';this.bodyEl.innerHTML='';zones.forEach((zone,index)=>{const label=zone.type==='PORTE'?zone.numeroPorte:zone.nomAffichage;let colorClass='';if(zone.type==='PORTE'){colorClass=gateConfig.gateProfil[zone.numeroPorte-1]==='1'?'gate-red':'gate-green';}else if(zone.type==='ROLL'){colorClass='gate-roll';}
this.headerEl.innerHTML+=`<div class="${colorClass}">${label}</div>`;const penaltyValue=penalties[index]||'0';const button=document.createElement('button');button.className=`penalty-button state-${penaltyValue}`;button.dataset.index=index;button.textContent=window.APP_TEXTS.dialogpenalty.penaltyValues[penaltyValue];this.bodyEl.appendChild(button);});}
_buildGlobalUI(config){const{heat,gateConfig,categoryName}=config;this.temporaryState={};heat.slots.forEach((slot)=>{if(slot.participant&&slot.participant.id){this.temporaryState[slot.prioDepart]=slot.heatResult.penalty||'0'.repeat(gateConfig.gateCount+2);}});this.titleEl.textContent=`${window.APP_TEXTS.dialogpenalty.globalPenaltyTitle} - ${heat.name} (${categoryName})`;const zones=ConfigurationPenalites.genererSequenceZones(gateConfig.gateCount,gateConfig.rollZoneAfterGate);const gridColumns=`50px 50px repeat(${zones.length}, minmax(60px, 1fr))`;this.headerEl.style.gridTemplateColumns=gridColumns;this.headerEl.innerHTML=`
            <div class="header-info">${window.APP_TEXTS.headerPrio}</div>
            <div class="header-info">${window.APP_TEXTS.headerBibBref}</div>
        `;zones.forEach(zone=>{const label=zone.type==='PORTE'?zone.numeroPorte:zone.nomAffichage;let colorClass='';if(zone.type==='PORTE'){colorClass=gateConfig.gateProfil[zone.numeroPorte-1]==='1'?'gate-red':'gate-green';}else if(zone.type==='ROLL'){colorClass='gate-roll';}
this.headerEl.innerHTML+=`<div class="${colorClass}">${label}</div>`;});this.bodyEl.innerHTML='';heat.slots.forEach(slot=>{if(!slot.participant||!slot.participant.id)return;const row=document.createElement('div');row.className='competitor-penalty-row';row.style.gridTemplateColumns=gridColumns;row.dataset.slotPrio=slot.prioDepart;const prioColors=['prio-red','prio-green','prio-blue','prio-yellow'];const prioLetter=window.APP_TEXTS.prioLetters[slot.prioDepart-1]||'-';row.innerHTML=`
                <div><span class="couleur-box ${prioColors[slot.prioDepart - 1]}">${prioLetter}</span></div>
                <div class="competitor-info-bib">${slot.participant.bib}</div>
            `;const penalties=this.temporaryState[slot.prioDepart].split('');zones.forEach((_,zoneIndex)=>{const button=document.createElement('button');const penaltyValue=penalties[zoneIndex]||'0';button.className=`penalty-button state-${penaltyValue}`;button.dataset.index=zoneIndex;button.textContent=window.APP_TEXTS.dialogpenalty.penaltyValues[penaltyValue];row.appendChild(button);});this.bodyEl.appendChild(row);});}
_attachEventListeners(){this.modalOverlay.addEventListener('click',(event)=>{const target=event.target;if(target===this.cancelBtn){this._handleCancel();return;}
if(target===this.saveBtn){this._handleSave();return;}
const penaltyButton=target.closest('.penalty-button');if(penaltyButton){this._handlePenaltyButtonClick(penaltyButton);}});}
_handlePenaltyButtonClick(button){const states=['0','2','5'];const penaltyIndex=parseInt(button.dataset.index,10);let currentState,updateFn;if(typeof this.temporaryState==='string'){currentState=this.temporaryState[penaltyIndex];updateFn=(newState)=>{let penalties=this.temporaryState.split('');penalties[penaltyIndex]=newState;this.temporaryState=penalties.join('');};}else{const row=button.closest('.competitor-penalty-row');const slotPrio=parseInt(row.dataset.slotPrio,10);currentState=this.temporaryState[slotPrio][penaltyIndex];updateFn=(newState)=>{let penalties=this.temporaryState[slotPrio].split('');penalties[penaltyIndex]=newState;this.temporaryState[slotPrio]=penalties.join('');};}
const currentIndex=states.indexOf(currentState);const nextState=states[(currentIndex+1)%states.length];updateFn(nextState);button.className=`penalty-button state-${nextState}`;button.textContent=window.APP_TEXTS.dialogpenalty.penaltyValues[nextState];}
_handleSave(){if(this.resolvePromise){this.resolvePromise(this.temporaryState);}
this._close();}
_handleCancel(){if(this.rejectPromise){this.rejectPromise(new Error("User cancelled penalty input."));}
this._close();}
_close(){this.modalOverlay.classList.remove('visible');this.temporaryState=null;this.resolvePromise=null;this.rejectPromise=null;}}