import{API_ENDPOINTS}from'./constants.js';export const SyncStatus=Object.freeze({SYNCED:'synced',PENDING:'pending',OFFLINE:'offline',SYNCING:'syncing'});export class SyncManager{constructor(competitionCode,deviceId){this.competitionCode=competitionCode;this.deviceId=deviceId;this.storageKey=`kcross_sync_queue_${competitionCode}_${deviceId}`;this.queue=[];this.status=SyncStatus.SYNCED;this.serverTimeOffset=0;this.isOnline=typeof navigator!=='undefined'?navigator.onLine:true;this.retryTimeouts=new Map();this.onStatusChange=null;this.onConflict=null;this.onOperationComplete=null;this.maxRetries=5;this.baseDelay=1000;this.maxDelay=30000;this._initialized=false;this._isProcessingQueue=false;}
async init(){if(this._initialized)return;this._initialized=true;this._loadQueue();if(typeof window!=='undefined'){window.addEventListener('online',()=>this._handleOnline());window.addEventListener('offline',()=>this._handleOffline());}
await this.syncServerTime();this._processQueue();}
async syncServerTime(){try{const clientBefore=Date.now();const response=await fetch(API_ENDPOINTS.GET_SERVER_TIME||'./api/api_get_server_time.php');const clientAfter=Date.now();const data=await response.json();if(data.success){const roundTrip=clientAfter-clientBefore;const estimatedServerTime=data.serverTime+(roundTrip/2);this.serverTimeOffset=estimatedServerTime-clientAfter;console.log(`[SyncManager] Décalage horloge: ${this.serverTimeOffset}ms`);}}catch(e){console.warn('[SyncManager] Impossible de synchroniser l\'heure serveur',e);}}
getServerTime(){return Date.now()+this.serverTimeOffset;}
_loadQueue(){try{const stored=localStorage.getItem(this.storageKey);this.queue=stored?JSON.parse(stored):[];}catch(e){console.error('[SyncManager] Erreur chargement queue',e);this.queue=[];}
this._updateStatus();}
_saveQueue(){try{localStorage.setItem(this.storageKey,JSON.stringify(this.queue));}catch(e){console.error('[SyncManager] Erreur sauvegarde queue',e);if(e.name==='QuotaExceededError'){alert("⚠️ MÉMOIRE PLEINE : Vos saisies ne sont plus enregistrées sur cette tablette. Connectez-vous au réseau pour vider la file d'attente ou contactez l'admin.");}}
this._updateStatus();}
_updateStatus(){const oldStatus=this.status;if(!this.isOnline){this.status=SyncStatus.OFFLINE;}else if(this.queue.length===0){this.status=SyncStatus.SYNCED;}else if(this.queue.some(op=>op.status==='processing')){this.status=SyncStatus.SYNCING;}else if(this.queue.some(op=>op.status==='pending'||op.status==='waiting_retry')){this.status=SyncStatus.PENDING;}else{this.status=SyncStatus.SYNCED;}
if(oldStatus!==this.status&&this.onStatusChange){this.onStatusChange(this.status,this.queue.length);}}
enqueue(action,payload,expectedLastModified=null){const operationId=`${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;const operation={id:operationId,action,payload:{...payload,expectedLastModified,modifiedBy:this.deviceId},createdAt:this.getServerTime(),retryCount:0,status:'pending'};const existingIndex=this._findExistingOperationIndex(action,payload);if(existingIndex>=0){const existingId=this.queue[existingIndex].id;if(this.retryTimeouts.has(existingId)){clearTimeout(this.retryTimeouts.get(existingId));this.retryTimeouts.delete(existingId);}
this.queue[existingIndex]=operation;}else{this.queue.push(operation);}
this._saveQueue();this._processQueue();return operationId;}
_findExistingOperationIndex(action,payload){return this.queue.findIndex(op=>{if(op.action!==action)return false;switch(action){case'update_penalite':case'update_status':case'update_place':return op.payload.code_Serie===payload.code_Serie&&op.payload.slot_Index===payload.slot_Index;case'validate_zone_penalties':return op.payload.heatId===payload.heatId&&op.payload.zoneIndex===payload.zoneIndex;case'update_heat_state':return op.payload.heatInfo===payload.heatInfo;default:return false;}});}
async _processQueue(){if(this._isProcessingQueue)return;if(!this.isOnline)return;this._isProcessingQueue=true;try{let pendingOps=this.queue.filter(op=>op.status==='pending');while(pendingOps.length>0&&this.isOnline){const op=pendingOps[0];await this._processOperation(op);pendingOps=this.queue.filter(op=>op.status==='pending');}}finally{this._isProcessingQueue=false;}}
async _processOperation(operation){if(!this.isOnline){return;}
operation.status='processing';this._saveQueue();try{const response=await fetch(API_ENDPOINTS.SAVEPOINT,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:operation.action,competitionCode:this.competitionCode,...operation.payload})});const result=await response.json();if(result.success){this._removeOperation(operation.id);console.log(`[SyncManager] Opération ${operation.id} synchronisée`);if(this.onOperationComplete){this.onOperationComplete({operation,newLastModified:result.newLastModified});}}else if(result.conflict){console.log(`[SyncManager] Conflit détecté pour ${operation.id}`);this._handleConflict(operation,result);}else if(result.locked){console.log(`[SyncManager] Série verrouillée pour ${operation.id}`);this._handleLocked(operation,result);}else{throw new Error(result.message||'Erreur serveur');}}catch(error){console.warn(`[SyncManager] Échec opération ${operation.id}:`,error.message);this._scheduleRetry(operation);}}
_removeOperation(operationId){this.queue=this.queue.filter(op=>op.id!==operationId);if(this.retryTimeouts.has(operationId)){clearTimeout(this.retryTimeouts.get(operationId));this.retryTimeouts.delete(operationId);}
this._saveQueue();}
_scheduleRetry(operation){operation.retryCount++;if(operation.retryCount>this.maxRetries){operation.status='failed';this._saveQueue();console.error(`[SyncManager] Opération ${operation.id} abandonnée après ${this.maxRetries} tentatives`);return;}
operation.status='waiting_retry';this._saveQueue();const delay=Math.min(this.baseDelay*Math.pow(2,operation.retryCount-1),this.maxDelay);console.log(`[SyncManager] Retry ${operation.id} dans ${delay}ms (tentative ${operation.retryCount})`);const timeoutId=setTimeout(()=>{this.retryTimeouts.delete(operation.id);operation.status='pending';this._saveQueue();this._processQueue();},delay);this.retryTimeouts.set(operation.id,timeoutId);}
_handleConflict(operation,serverResponse){this._removeOperation(operation.id);if(this.onConflict){this.onConflict({operation,serverLastModified:serverResponse.serverLastModified,modifiedBy:serverResponse.modifiedBy,message:`Modification ignorée - déjà traitée par ${serverResponse.modifiedBy || 'un autre utilisateur'}`});}}
_handleLocked(operation,serverResponse){this._removeOperation(operation.id);if(this.onConflict){this.onConflict({operation,locked:true,state:serverResponse.state,message:serverResponse.message||'Série verrouillée'});}}
_handleOnline(){console.log('[SyncManager] Connexion rétablie');this.isOnline=true;this._updateStatus();this.retryFailed();this._processQueue();}
_handleOffline(){console.log('[SyncManager] Connexion perdue');this.isOnline=false;this._updateStatus();}
getStatus(){return{status:this.status,pendingCount:this.queue.filter(op=>op.status==='pending'||op.status==='processing'||op.status==='waiting_retry').length,failedCount:this.queue.filter(op=>op.status==='failed').length,isOnline:this.isOnline};}
retryFailed(){this.queue.forEach(op=>{if(op.status==='failed'){if(this.retryTimeouts.has(op.id)){clearTimeout(this.retryTimeouts.get(op.id));this.retryTimeouts.delete(op.id);}
op.retryCount=0;op.status='pending';}});this._saveQueue();this._processQueue();}
clearQueue(){this.retryTimeouts.forEach(t=>clearTimeout(t));this.retryTimeouts.clear();this.queue=[];this._saveQueue();}
hasPendingOperation(action,criteria){return this.queue.some(op=>{if(op.action!==action)return false;const p=op.payload;if(action==='update_heat_state'||action==='force_validate_heat'){const opHeatId=p.heatInfo||p.heatId||p.code_Serie;return parseInt(opHeatId,10)===parseInt(criteria.heatId,10);}
if(action==='validate_zone_penalties'){return parseInt(p.heatId,10)===parseInt(criteria.heatId,10)&&parseInt(p.zoneIndex,10)===parseInt(criteria.zoneIndex,10);}
if(action==='update_place'||action==='update_status'||action==='update_penalite'){const opHeatId=p.code_Serie||p.heatId||p.heatInfo;const matchHeat=parseInt(opHeatId,10)===parseInt(criteria.heatId,10);const matchSlot=criteria.slotIndex!==undefined?(parseInt(p.slot_Index||p.slotIndex,10)===parseInt(criteria.slotIndex,10)):true;return matchHeat&&matchSlot;}
return false;});}}