import{escapeHtml,notifyError,renderSpecialStatusOptions,createPenaltySummaryHTML,loadHTMLTemplate,applyStaticTexts,changerOrientation}from'./utils.js';import{ConfigurationPenalites,Serie,Participant}from'./engine.js';import{SpecialStatus,HeatState}from'./constants.js';import{BasePeripheriqueUI}from'./base_peripherique_ui.js';import{PenaltyModal}from'./penaltyModal.js';import{RaceMonitorWidget}from'./raceMonitorWidget.js';import{loadLanguage}from'./languageManager.js';class JugementUI extends BasePeripheriqueUI{constructor(){super();this.appName='jugement';this.persistenceManager=null;this.container=document.getElementById('start-list-container');this.upcomingHeats=[];this.currentHeatIndex=0;this.nbSerieCache=30;this.competitionCode=null;this.gateCount;this.rollZone;this.detailPortes;this.temporaryPenaltyState=null;this.individualPenaltyModal=null;this.globalPenaltyModal=null;this.raceMonitorWaiting=null;this.raceMonitorJudging=null;this._waitingWidgetInitialized=false;this.useSyncManager=true;}
async tick(){const currentHeat=(this.upcomingHeats&&this.upcomingHeats[this.currentHeatIndex])?this.upcomingHeats[this.currentHeatIndex]:null;if(!currentHeat||!currentHeat.id){await this.fetchAndDisplayHeats();}}
_configureFetchParameters(){this.fetchState='4';this.fetchZone='nostart';this.noHeatsMessage=window.APP_TEXTS.jugement.noHeatsAvailable;}
renderSingleHeat(heat){super.renderSingleHeat(heat);this._initJudgingWidget(heat);}
_onNoHeatsRendered(){this._initWaitingWidget();}
_initWaitingWidget(){const container=document.getElementById('waiting-widget-container');if(!container)return;if(this.raceMonitorWaiting){this.raceMonitorWaiting.destroy();}
this.raceMonitorWaiting=new RaceMonitorWidget(container,'top',{showHeader:true,showGlobalNumber:false,showForceButton:true,showStatusBadge:false,persistenceManager:this.persistenceManager,pollingInterval:this.delay,onForceClick:async(heat)=>{const choice=await this.showCustomConfirm(window.APP_TEXTS.jugement.confirmForceTitle,window.APP_TEXTS.jugement.confirmForceMessage,[{text:window.APP_TEXTS.cancel,value:'cancel',class:'secondary'},{text:window.APP_TEXTS.jugement.btnConfirmForce,value:'confirm',class:'danger'}]);if(choice!=='confirm')return;try{const result=await this.persistenceManager.forceValidateHeat(heat.id);if(result.success){await this.fetchAndDisplayHeats();}}catch(e){console.error(`[JugementUI] Erreur force validation:`,e);alert(`Erreur lors du forçage : ${e.message}`);}}});this.raceMonitorWaiting.startPolling();}
_postProcessHeats(heatsFromAPI){return heatsFromAPI.map(rawHeat=>{this.gateCount=rawHeat.gateCount||8;this.rollZone=rawHeat.rollZoneAfterGate!==null?rawHeat.rollZoneAfterGate:2;this.detailPortes=rawHeat.detailPortes!==null?rawHeat.detailPortes:'0'.repeat(this.gateCount+1);const serie=new Serie(rawHeat.name,rawHeat.roundKey);serie.id=rawHeat.id;serie.startTime=rawHeat.startTime;serie.etat=rawHeat.etat;serie.globalHeatNumber=rawHeat.globalHeatNumber;serie.categoryKey=rawHeat.categoryKey;serie.zonesJugees=rawHeat.zonesJugees||'';rawHeat.slots.forEach(rawSlot=>{const slotIndex=rawSlot.prioDepart-1;if(slotIndex>=0&&slotIndex<serie.slots.length){if(rawSlot.participant&&rawSlot.participant.id){const participant=new Participant(rawHeat.categoryKey,999,rawSlot.participant.bib,rawSlot.participant.name);participant.id=rawSlot.participant.id;serie.slots[slotIndex].participant=participant;}else{serie.slots[slotIndex].participant=null;}
serie.slots[slotIndex].prioDepart=rawSlot.prioDepart;let penalty=rawSlot.participant.penalite;serie.slots[slotIndex].heatResult={order:rawSlot.participant.ordre_arrivee||null,penalty:penalty,specialStatus:rawSlot.participant.specialStatus||null,finalRank:'-'};}});return serie;});}
showCustomConfirm(title,message,buttons){return new Promise((resolve)=>{const overlay=document.getElementById('custom-dialog-overlay');const titleEl=document.getElementById('dialog-title');const messageEl=document.getElementById('dialog-message');const actionsEl=document.getElementById('dialog-actions');titleEl.textContent=title;messageEl.textContent=message;actionsEl.innerHTML='';buttons.forEach(btnInfo=>{const button=document.createElement('button');button.textContent=btnInfo.text;button.dataset.value=btnInfo.value;if(btnInfo.class)button.classList.add(btnInfo.class);actionsEl.appendChild(button);});const clickHandler=(event)=>{const clickedButton=event.target.closest('button');if(clickedButton){overlay.classList.remove('visible');actionsEl.removeEventListener('click',clickHandler);resolve(clickedButton.dataset.value);}};actionsEl.addEventListener('click',clickHandler);overlay.classList.add('visible');});}
_renderTable(heat){heat.calculateAndApplyRanking();const tableTemplate=document.getElementById('template-jugement-table');const rowTemplate=document.getElementById('template-jugement-row');if(!tableTemplate||!rowTemplate){console.error("Un ou plusieurs templates de jugement sont manquants !");return"<table><tr><td>Erreur de template</td></tr></table>";}
const tableClone=tableTemplate.content.cloneNode(true);applyStaticTexts(window.APP_TEXTS,tableClone);const tbody=tableClone.querySelector('tbody');const activeParticipantsCount=heat.slots.filter(slot=>slot.participant&&slot.participant.id).length;heat.slots.forEach(slot=>{if(!slot.participant||!slot.participant.id)return;const rowClone=rowTemplate.content.cloneNode(true);const tr=rowClone.querySelector('tr');this._populateTableRow(tr,slot,activeParticipantsCount);tbody.appendChild(rowClone);});const wrapper=document.createElement('div');wrapper.appendChild(tableClone);return wrapper.innerHTML;}
_populateTableRow(tr,slot,activeParticipantsCount){tr.dataset.slotPrio=slot.prioDepart;const prioColorsClasses=['prio-red','prio-green','prio-blue','prio-yellow'];const prioLetters=window.APP_TEXTS.prioLetters;const colorIndex=slot.prioDepart-1;const prioVariables={'1':{color:'var(--color-prio-red)',textColor:'var(--color-text-light)'},'2':{color:'var(--color-prio-green)',textColor:'var(--color-text-light)'},'3':{color:'var(--color-prio-blue)',textColor:'var(--color-text-light)'},'4':{color:'var(--color-prio-yellow)',textColor:'var(--color-text-dark)'}};const styleVars=prioVariables[slot.prioDepart];if(styleVars){tr.style.setProperty('--prio-color',styleVars.color);tr.style.setProperty('--prio-text-color',styleVars.textColor);}
tr.querySelector('.col-prio .couleur-box').className=`couleur-box ${prioColorsClasses[colorIndex]}`;tr.querySelector('.col-prio .couleur-box').textContent=prioLetters[colorIndex];tr.querySelector('.col-bib').textContent=slot.participant.bib;tr.querySelector('.col-noms').textContent=escapeHtml(slot.participant.name);const rankButtonGroup=tr.querySelector('.rank-button-group');let rankButtonsHtml='';for(let i=1;i<=activeParticipantsCount;i++){const rank=String(i);const isChecked=String(slot.heatResult.order)===rank?'checked':'';rankButtonsHtml+=`<label><input type="radio" name="rank-${slot.prioDepart}" value="${rank}" data-action="update-local" data-type="order" ${isChecked}><span>${rank}</span></label>`;}
rankButtonGroup.innerHTML=rankButtonsHtml;tr.querySelector('.col-pen-details').innerHTML=createPenaltySummaryHTML(slot.heatResult.penalty,{heatResult:slot.heatResult,gateCount:this.gateCount,rollZoneAfterGate:this.rollZone});tr.querySelector('.col-pen-details').dataset.slotPrio=slot.prioDepart;const statusSelect=tr.querySelector('.status-select');statusSelect.innerHTML=`<option value="">-</option>${renderSpecialStatusOptions(slot.heatResult.specialStatus)}`;tr.querySelector('.col-clt').textContent=slot.heatResult.finalRank||'-';}
_syncHeatViewWithState(heat){const heatContainer=this.container.querySelector('.heat-block-start');if(!heatContainer)return;heat.slots.forEach(slot=>{if(!slot.participant)return;const activeParticipantsCount=heat.slots.filter(s=>s.participant&&s.participant.id).length;const row=heatContainer.querySelector(`tr[data-slot-prio="${slot.prioDepart}"]`);if(row){this._populateTableRow(row,slot,activeParticipantsCount);}});}
_getMainActionButtons(heat){return`
            <div class="widget-zone widget-zone-left" id="judging-widget-container"></div>
            <div class="action-buttons-spacer"></div>
            <button class="btn-en-place btn-validate" data-action="validate-heat" data-heat-id="${heat.id}">${window.APP_TEXTS.btnValidateClt}</button>
        `;}
_initJudgingWidget(heat){const container=document.getElementById('judging-widget-container');if(!container)return;if(this.raceMonitorWaiting){this.raceMonitorWaiting.stopPolling();}
this.raceMonitorJudging=new RaceMonitorWidget(container,'top',{showHeader:false,showGlobalNumber:false,showStatusBadge:false,penaltyZonesOnly:true,pollingInterval:0,title:window.APP_TEXTS?.jugement?.widgetTitle||"État de saisie des zones"});const adaptedHeat=this._adaptHeatForWidget(heat);this.raceMonitorJudging.update(adaptedHeat,{gateCount:this.gateCount,rollZoneAfterGate:this.rollZone,detailPortes:this.detailPortes});}
_adaptHeatForWidget(heat){return{id:heat.id,name:heat.name,roundKey:heat.roundKey,categoryKey:heat.categoryKey,etat:heat.etat,globalHeatNumber:heat.globalHeatNumber,zonesJugees:heat.zonesJugees||'',slots:heat.slots.map(slot=>({prioDepart:slot.prioDepart,participant:slot.participant?{id:slot.participant.id,bib:slot.participant.bib,name:slot.participant.name,ordre_arrivee:slot.heatResult?slot.heatResult.order:null,specialStatus:slot.heatResult?slot.heatResult.specialStatus:null}:null}))};}
initializeModals(){this.individualPenaltyModal=new PenaltyModal('penalty-modal-overlay');this.globalPenaltyModal=new PenaltyModal('global-penalty-modal-overlay');}
async handleOpenIndividualPenaltyModal(dataset){if(!this.individualPenaltyModal)return;const slotPrio=parseInt(dataset.slotPrio,10);const heat=this.upcomingHeats[this.currentHeatIndex];const competitorIndex=heat.slots.findIndex(s=>s.prioDepart===slotPrio);const config={type:'individual',heat:heat,context:'jugement',competitorIndex:competitorIndex,gateConfig:{gateCount:this.gateCount,rollZoneAfterGate:this.rollZone,gateProfil:this.detailPortes}};try{const newPenalties=await this.individualPenaltyModal.open(config);heat.slots[competitorIndex].heatResult.penalty=newPenalties;this.renderCurrentHeat();}catch(error){}}
async handleOpenGlobalPenaltyModal(){if(!this.globalPenaltyModal)return;const heat=this.upcomingHeats[this.currentHeatIndex];const config={type:'global',heat:heat,context:'jugement',gateConfig:{gateCount:this.gateCount,rollZoneAfterGate:this.rollZone,gateProfil:this.detailPortes}};try{const newPenaltiesBySlot=await this.globalPenaltyModal.open(config);for(const slotPrio in newPenaltiesBySlot){const slot=heat.slots.find(s=>s.prioDepart===parseInt(slotPrio,10));if(slot){slot.heatResult.penalty=newPenaltiesBySlot[slotPrio];}}
this.renderCurrentHeat();}catch(error){}}
updateLocalState(target){const slotPrio=parseInt(target.closest('tr').dataset.slotPrio,10);const type=target.dataset.type;const value=target.value;const heat=this.upcomingHeats[this.currentHeatIndex];if(!heat)return;const slot=heat.slots.find(s=>s.prioDepart===slotPrio);if(!slot)return;if(type==='order'){slot.heatResult.order=value||null;if(value)slot.heatResult.specialStatus=null;}else if(type==='status'){slot.heatResult.specialStatus=value||null;if(value)slot.heatResult.order=null;}
heat.calculateAndApplyRanking();this._syncHeatViewWithState(heat);}
async handleValidateClick(heatId){const button=this.container.querySelector('[data-action="validate-heat"]');const heatToValidate=this.upcomingHeats[this.currentHeatIndex];if(!heatToValidate.areAllActiveResultsEntered()){notifyError(window.APP_TEXTS.jugement.alertIncompleteRanks);return;}
button.disabled=true;button.textContent=window.APP_TEXTS.btnValidating;try{heatToValidate.slots.forEach(slot=>{if(slot.participant&&slot.participant.rankTT>0)
if(slot.heatResult.penalty===null)
slot.heatResult.penalty='0'.repeat(this.gateCount+2);})
heatToValidate.calculateAndApplyRanking();heatToValidate.etat=HeatState.OFFICIEL;const slotsData=heatToValidate.slots.filter(s=>s.participant).map(s=>({prioDepart:s.prioDepart,heatResult:s.heatResult}));await this.persistenceManager.validateHeatResults(heatId,slotsData);this.upcomingHeats.splice(this.currentHeatIndex,1);if(this.currentHeatIndex>=this.upcomingHeats.length&&this.currentHeatIndex>0){this.currentHeatIndex--;}
if(this.upcomingHeats.length>0){this.renderCurrentHeat();}else{await this.fetchAndDisplayHeats();}}catch(error){notifyError(`${window.APP_TEXTS.jugement.alertErrorSaving} ${error.message}`);button.disabled=false;button.textContent=window.APP_TEXTS.btnValidateClt;}}}
document.addEventListener('DOMContentLoaded',async()=>{changerOrientation('auto');await loadLanguage(['common','peripheriques']);await loadHTMLTemplate('modals.html',document.body);const jugementApp=new JugementUI();jugementApp.initializeModals();document.body.addEventListener('click',(event)=>{const target=event.target.closest('[data-action]');if(!target)return;const action=target.dataset.action;switch(action){case'validate-heat':jugementApp.handleValidateClick(target.dataset.heatId);break;case'next-heat':jugementApp.handleNextHeat();break;case'previous-heat':jugementApp.handlePreviousHeat();break;case'refresh-data':jugementApp.fetchAndDisplayHeats();break;case'open-penalty-modal':jugementApp.handleOpenIndividualPenaltyModal(target.dataset);break;case'open-global-penalty-modal':jugementApp.handleOpenGlobalPenaltyModal();break;case'update-local':if(target.matches('input[type="radio"]')){jugementApp.updateLocalState(target);}
break;}});document.body.addEventListener('change',(event)=>{const target=event.target.closest('[data-action="update-local"]');if(target&&target.matches('select')){jugementApp.updateLocalState(target);}});window.addEventListener('beforeunload',()=>jugementApp.destroy());jugementApp.initialize();});